### DISCUSSION TITLE
No exception is received when creating CR with unknown fields

### DISCUSSION THREAD

**Discussion by ghost** [fabric8io/kubernetes-client#4191] [Q&A]
Hi, 
when I apply CRs with unknown fields using `MixedOperation` I get no exception. On the other hand when I try to apply the same CR with `kubectl` exception is there.
What's more strange for me, fabric8 does throw exceptions when field value types are mismatched, however, no exception when field itself is unknown in CRD.

Is this an expected behavior from fabric8 ? is there any feature I can enable to get the exception ?

using `kubernetes-client:5.9.0` checked on `5.12.2` and got the same behavior

this is my CRD:

```YAML
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myresources.example.com
spec:
  conversion:
    strategy: None
  group: example.com
  names:
    kind: MyResource
    listKind: MyResourceList
    plural: myresources
    singular: myresource
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.type
      name: Type
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            description: Specification of desired box
            properties:
              imageName:
                description: docker image repository URL
                type: string
              imageVersion:
                description: docker image tag
                type: string
        required:
        - spec
    served: true
    storage: true
```

and this is the java code:

```java
public class Example {
    @Group("example.com")
    @Version("v1")
    @Kind("MyResource")
    public static class MyCustomResource extends CustomResource<Object, Object> implements Namespaced {
    }

    public static void main(String[] args) {
        try (KubernetesClient client = new DefaultKubernetesClient()) {
            var operation = client.resources(MyCustomResource.class);
            var customResource = new MyCustomResource();
            customResource.setKind("MyResource");
            customResource.setApiVersion("example.com/v1");
            customResource.setMetadata(new ObjectMeta());
            customResource.getMetadata().setName("example-cr");
            customResource.setSpec(new HashMap<>() {{
                put("imageName", "some-test-image");
                put("imageVersion", "0.0.1");
                put("unknownField", "unknownField");

            }});

            operation.inNamespace("example").createOrReplace(customResource);

        }
    }
}

```
