### DISCUSSION TITLE
How to set the nodeSelector for deployment?

### DISCUSSION THREAD

**Discussion by hanming-nls** [fabric8io/kubernetes-client#4779] [Q&A] [answered]
May I know what is the equivalent of setting the nodeSelector in the yaml under the spec as below

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
  nodeSelector:
    nodetype: worker
```

It seems that the DeploymentSpec object do include the nodeSelector but the DeploymentSpec selector uses a LabelSelector instead of a NodeSelect.

I'm not sure how can I specify the NodeSelector in the DeploymentSpec, thus, would greatly appreciate any advice.
