### DISCUSSION TITLE
use kubernetes-client informer, but pod finished event delayed by 3 hours.

### DISCUSSION THREAD

**Discussion by bestbugwriter** [fabric8io/kubernetes-client#5083] [Q&A]
My kubernetes-client version
```
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>6.4.1</version>
```

My Kubernetes server version

```
serverVersion:
  buildDate: "2023-03-01T03:20:55Z"
  compiler: gc
  gitCommit: d0fc63469d8b77701822b1cbca6ea981a87a0c5c
  gitTreeState: clean
  gitVersion: v1.20.11-aliyun.1
  goVersion: go1.15.15
  major: "1"
  minor: 20+
  platform: linux/amd64
```

pod submit time 18:06, end time 18:08, but informer Callback state Finished at 21:16 and 22:14, so why it delay for such a long time？ Are there any other debugging methods that we need to operate.

![image](https://user-images.githubusercontent.com/4133268/234750943-48bec83c-9c92-466a-bb9f-2c5789c35213.png)
