### DISCUSSION TITLE
How do I create a VolcanoJob?

### DISCUSSION THREAD

**Discussion by hzp01** [fabric8io/kubernetes-client#5653] [Q&A] [answered]
How do I create a VolcanoJob?
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-job
spec:
  minAvailable: 3
  schedulerName: volcano
  priorityClassName: high-priority
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  volumes:
    - mountPath: "/myinput"
    - mountPath: "/myoutput"
      volumeClaimName: "testvolumeclaimname"
      volumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "my-storage-class"
        resources:
          requests:
            storage: 1Gi
  tasks:
    - replicas: 6
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: "1"
          restartPolicy: OnFailure
```

**Comment by rohanKanojia** [comment, marked as answer]
In which version `batch.volcano.sh/v1alpha1` Job was introduced? . Our Volcano Extension only supports v1beta1 model types till `v1.3.0-k8s1.18.3`.

You should be able to create it using [GenericKubernetesResource API](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md#resource-typeless-api)

**Reply by hzp01** [reply]
May I ask if there is any issue with the following code? Seeking guidance, thank you
```
        ResourceDefinitionContext context = new ResourceDefinitionContext.Builder()
            .withKind("Job")
            .withGroup("batch.volcano.sh")
            .withVersion("v1alpha1").build();
        GenericKubernetesResource volcanoJob = client.genericKubernetesResources(context)
            .load(VolcanoUtil.class.getClassLoader().getResourceAsStream("volcano-job.yaml"))
            .serverSideApply();
```
volcano-job.yaml 
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-1
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: test
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: nginx
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        spec:
          containers:
            - command:
              - sleep
              - 10m
              image: nginx:latest
              name: nginx
              resources:
                requests:
                  cpu: 1
                limits:
                  cpu: 1
          restartPolicy: Never
```
![image](https://github.com/fabric8io/kubernetes-client/assets/32353592/f5468982-83ef-43ce-bbf2-67296e38662e)
