### DISCUSSION TITLE
I want to implement distributed TensorFlow jobs, and the YAML template follows this format. Do I need to split this YAML into separate files for job and service creation?

### DISCUSSION THREAD

**Discussion by hzp01** [fabric8io/kubernetes-client#5667] [Q&A]
I want to implement distributed TensorFlow jobs, and the YAML template follows this format. Do I need to split this YAML into separate files for job and service creation?
```
apiVersion: batch/v1
kind: Job
metadata:
  name: worker-0
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node2
      restartPolicy: Never
      containers:
      - name: worker-0
        image: tensorflow/tensorflow:latest
        imagePullPolicy: IfNotPresent
        workingDir: /home/zhoubj/tfmmw
        env:
        - name: TF_CONFIG
          value: '{"cluster":{"worker":["keras-with-strategy-worker-0:3333", "keras-with-strategy-worker-1:3333"]},"task":{"index":0,"type":"worker"}}'
        volumeMounts:
        - name: tfmmw-volume
          mountPath: /home/zhoubj
        command: ["/bin/bash", "-c"]
        args: ["python main.py"]
        ports:
        - containerPort: 3333
        resources:
          limits:
            cpu: "4"
            memory: "2Gi"
          requests:
            cpu: "2"
            memory: "1024Mi"
      volumes:
      - name: tfmmw-volume
        hostPath:
          path: /home/zhoubj
---
apiVersion: v1
kind: Service
metadata:
  name: keras-with-strategy-worker-0
spec:
  selector:
    job-name: worker-0
  ports:
  - port: 3333
    targetPort: 3333
```
