### DISCUSSION TITLE
May I ask, what is the URL used by the underlying HttpClient when executing List<HasMetadata> foo = client.resourceList(items).inNamespace("default").serverSideApply();?

### DISCUSSION THREAD

**Discussion by hzp01** [fabric8io/kubernetes-client#5675] [Q&A]
When executing DefaultKubernetesClient client = DefaultKubernetesClientCreate.getDefaultKubernetesClient();, the output indicated 'Using httpclient io.fabric8.kubernetes.client.okhttp.OkHttpClientFactory factory.' However, in which line of code can the URL be seen when executing List<HasMetadata> foo = client.resourceList(items).inNamespace("default").serverSideApply();?
```
        String yaml = "k8s-tensorflow-job.yaml";
        DefaultKubernetesClient client = DefaultKubernetesClientCreate.getDefaultKubernetesClient();
        List<HasMetadata> items = client.load(K8sTensorflowJobCreate.class.getClassLoader().getResourceAsStream(yaml)).items();
        List<HasMetadata> foo = client.resourceList(items).inNamespace("default").serverSideApply();
        System.out.println(foo);
```
```
apiVersion: batch/v1
kind: Job
metadata:
  name: worker-0
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node2
      restartPolicy: Never
      containers:
      - name: worker-0
        image: tensorflow/tensorflow:latest
        imagePullPolicy: IfNotPresent
        workingDir: /home/zhoubj/tfmmw
        env:
        - name: TF_CONFIG
          value: '{"cluster":{"worker":["keras-with-strategy-worker-0:3333", "keras-with-strategy-worker-1:3333"]},"task":{"index":0,"type":"worker"}}'
        volumeMounts:
        - name: tfmmw-volume
          mountPath: /home/zhoubj
        command: ["/bin/bash", "-c"]
        args: ["python main.py"]
        ports:
        - containerPort: 3333
        resources:
          limits:
            cpu: "4"
            memory: "2Gi"
          requests:
            cpu: "2"
            memory: "1024Mi"
      volumes:
      - name: tfmmw-volume
        hostPath:
          path: /home/zhoubj
---
apiVersion: v1
kind: Service
metadata:
  name: keras-with-strategy-worker-0
spec:
  selector:
    job-name: worker-0
  ports:
  - port: 3333
    targetPort: 3333
```
