### DISCUSSION TITLE
How to have java-generator-maven-plugin reuse an existing enum?

### DISCUSSION THREAD

**Discussion by k-wall** [fabric8io/kubernetes-client#7015] [Q&A] [answered]
In our application we use CRD -> Java POJO.

In my CRD i have a field `protocol` which is defined like this:

```yaml
                    protocol:
                      description: "Protocol specifies the network protocol this ingress expects to receive."
                      type: string
                      enum: ["TCP", "TLS"]
```

`java-generator-maven-plugin` is creating a `Protocol` enum as a inner class of class called ClusterIP.  The same protocol object will appear elsewhere in the CRD model for the application.  I don't want several definitions of the Protocol enum. I'd like to get the generator use the same definition.

I tried an `existingJavaTypes` but it is ignored.  

```xml
                    <existingJavaTypes>

                        <io.kroxylicious.kubernetes.api.v1alpha1.kafkaproxyingressspec.ClusterIP.Protocol>
                            io.kroxylicious.kubernetes.api.common.Protocol
                        </io.kroxylicious.kubernetes.api.v1alpha1.kafkaproxyingressspec.ClusterIP.Protocol>

                    </existingJavaTypes>
```

I debugged the java-generator-maven-plugin and I see that io.fabric8.java.generator.nodes.JEnum#generateJava doesn't even consider the possibility that the type might have been defined as an existingJavaTypes.

Am I missing something? I'm inexperienced with java-generator-maven-plugin so I could be on the wrong track.
