### ISSUE TITLE
Bug: access-token vs. id-token

### ISSUE THREAD

**Issue by AlainRoy** [fabric8io/kubernetes-client#1177]
I believe that I've found a bug in the fabric8 Kubernetes client. We were testing it with a service (VMware Kubernetes Engine) that uses OIDC and it failed to authenticate. It gave an error like:

```
Cannot access cluster for detecting mode: Failure executing: GET at: https://HOSTNAME/. Message: Unauthorized! Token may have expired! Please log-in again. Unauthorized
```

The token is stored in kubectl as an OIDC auth-provider, and it's called "id-token". An edited version from my kubectl file looks like this:

```
users:
- name: me
  user:
    auth-provider:
      config:
        client-id: 86a...
        client-secret: 0df...
        id-token: eyJhbGciOiJSU...
        idp-certificate-authority: /var/folders/...
        idp-issuer-url: https://XXX
        refresh-token: ""
```

I believe that `id-token` is correct, based on my reading of the go-client, which is used by kubectl. From https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/oidc/oidc.go#L43 

```
cfgIDToken                  = "id-token"
```

If I look in `kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java`, I see:

```
  private static final String ACCESS_TOKEN = "access-token";
...
          if (Utils.isNullOrEmpty(config.getOauthToken()) && currentAuthInfo.getAuthProvider() != null && !Utils.isNullOrEmpty(currentAuthInfo.getAuthProvider().getConfig().get(ACCESS_TOKEN))) {
            config.setOauthToken(currentAuthInfo.getAuthProvider().getConfig().get(ACCESS_TOKEN));
          }
```

I manually edited my kubectl file to rename `id-token` to `access-token`, and I re-ran `mvn fabric8 deploy` and it worked. 

I appreciate why you use ACCESS_TOKEN, because it is used for other auth providers. Probably this code needs to be adapted to use either access-token or id-token, depending on what is available.

I'd offer a patch, but I probably won't get to it soon. Hopefully this bug description is sufficient for you to understand and address the issue. (And if you really think hard about it, you probably want to be able to use refresh-tokens, but that starts to be more work...)
