### ISSUE TITLE
Is it possible to create a HPA based on custom metrics?

### ISSUE THREAD

**Issue by ntpan** [fabric8io/kubernetes-client#1186]
I have the following hpa.yaml file which looks up custom pod metrics (http_requests_seconds_rate).
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: the-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: the-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: http_requests_seconds_rate
      targetAverageValue: 20
```

I'd like to create this exact HPA using kubernetes-client but can't figure out how to provide the "metrics: ..." part.
Is this not yet supported or am I missing something?
