### ISSUE TITLE
NoClassDefFoundError when trying to load an OpenShift template with generated parameters

### ISSUE THREAD

**Issue by amisevsk** [fabric8io/kubernetes-client#1340]
### Description
When trying to `load()` an OpenShift template with [generated parameters](https://docs.openshift.com/container-platform/3.6/dev_guide/templates.html#writing-parameters), an exception is thrown:
```
java.lang.NoClassDefFoundError: com/mifmif/common/regex/Generex
```

It originates from the line [here](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java#L393)

Sample yaml:
```yaml
kind: Template
apiVersion: v1
objects:
- 
  apiVersion: v1
  kind: Pod
  metadata:
    name: sample
  spec:
    containers:
    - name: sample
      image: 'centos:latest'
parameters:
- name: TEST
  generate: expression
  from: "[A-Z]{12}"
```

Then calling
```java
String yaml = /* the yaml above */
kubernetesClient.load(new ByteArrayInputStream(yaml.getBytes())).get();
```
throws as above.

### Version
kubernetes-client 4.1.0
