### ISSUE TITLE
Scala CustomResource does not conform to method customResources's type parameter bounds

### ISSUE THREAD

**Issue by ifilonenko** [fabric8io/kubernetes-client#1341]
EDIT: Works with scala 2.11 but not 2.12
I have been trying to create a CustomResource programatically using the JavaSDK via Scala. 

I implemented the following in Scala (mimicing the examples found here: https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/crds) to implement the necessary classes to create the customResource.

```scala
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.annotation.JsonDeserialize
import io.fabric8.kubernetes.api.builder.{Function => func}
import io.fabric8.kubernetes.api.model.{KubernetesResource, PodTemplateSpec}
import io.fabric8.kubernetes.client.{CustomResource, CustomResourceDoneable, CustomResourceList}

@JsonDeserialize(
  using = classOf[JsonDeserializer.None]
)
private[k8s] class ExecPodScaler(var spec: ExecPodScalerSpec) extends CustomResource {
  override def toString: String = {
    s"ExecPodScaler{" +
      s"apiVersion='$getApiVersion'\'" +
      s"kind='$getKind'\'" +
      s"metadata='$getMetadata'\'" +
      s"spec='$getSpec'}"
  }
  def getSpec: ExecPodScalerSpec = spec
  def setSpec(_spec: ExecPodScalerSpec): Unit = {
    spec = _spec
  }
}

@JsonDeserialize(
  using = classOf[JsonDeserializer.None]
)
private[k8s] class ExecPodScalerSpec(
  var numExecPods: Int,
  var podTemplates: Seq[PodTemplateSpec]) extends KubernetesResource[ExecPodScaler] {
  override def toString: String = {
    s"ExecPodScalerSpec{" +
      s"numExecPods='$getNumExecPods'\'" +
      s"podTemplates='$getPodTemplate'}"
  }

  def getNumExecPods: Int = numExecPods
  def setNumExecPods(_numExecPods: Int): Unit = {
    numExecPods = _numExecPods
  }

  def getPodTemplate: Seq[PodTemplateSpec] = podTemplates
  def setPodTemplates(_podTemplates: Seq[PodTemplateSpec]): Unit = {
    podTemplates = _podTemplates
  }
}

@JsonDeserialize(
  using = classOf[JsonDeserializer.None]
)
private[k8s] class ExecPodScalerList extends CustomResourceList[ExecPodScaler]

@JsonDeserialize(
  using = classOf[JsonDeserializer.None]
)
private[k8s] class DoneableExecPodScaler(
    val ecs: ExecPodScaler, val function: func[ExecPodScaler, ExecPodScaler])
  extends CustomResourceDoneable[ExecPodScaler](ecs, function) {
}
```
However, upon running: 
```scala
kubernetesClient.customResources[
      ExecPodScaler, ExecPodScalerList, DoneableExecPodScaler](
      execPodScalerCRD,
      classOf[ExecPodScaler],
      classOf[ExecPodScalerList],
      classOf[DoneableExecPodScaler]).inNamespace(namespace)
```
I get the following error: 
```
error: type arguments [ExecPodScaler,ExecPodScalerList,DoneableExecPodScaler]
 do not conform to method customResources's type parameter bounds
 [T <: io.fabric8.kubernetes.api.model.HasMetadata,
 L <: io.fabric8.kubernetes.api.model.KubernetesResourceList[
_ <: io.fabric8.kubernetes.api.model.HasMetadata],
 D <: io.fabric8.kubernetes.api.model.Doneable[T]]
    epsClient = kubernetesClient.customResources[
                                                ^
```
even tho by extending CustomResource, CustomResourceList, and CustomResourceDonable it should conform to type parameters. 

Thanks! Any help would be appreciated!!!

**Comment by erikerlandson** [comment]
A couple other notes on this:
1. @ifilonenko found that this compiled correctly on scala 2.11 - the problem shows up when compiling against 2.12
2. The signature that scala's error message is reporting is different than the signature implied by the java code for `customResources` method - from the scala side it looks as if scala is mis-interpreting the signature and that is what is causing the failure to resolve the method call.

**Comment by erikerlandson** [comment]
cc @skonto

**Comment by skonto** [comment]
@lrytz is this is a known issue? ^^^

**Comment by skonto** [comment]
@ifilonenko could you provide some context (execPodScalerCRD?

**Comment by ifilonenko** [comment]
It is just an existing CRD that I find using: 
```java
    public CustomResourceDefinition findCRD() {
        try {
            CustomResourceDefinitionList crds = client.customResourceDefinitions().list();
            List<CustomResourceDefinition> crdsItems = crds.getItems();
            logger.info("Number of crds: " + crdsItems.size());
            for ( CustomResourceDefinition crd: crdsItems ) {
                if (crd.getSpec().getGroup().toString().equals(EPS_CRD_GROUP) &&
                    crd.getSpec().getNames().getKind().toString().equals(EPS_KIND)) {
                    return crd;
                }
            }
        } catch (KubernetesClientException e) {
            logger.error("Problem with retrieving CRDs with Kubernetes Client", e);
        } catch (Exception e) {
            logger.error(e.getMessage(), e);
        }
        return null;
    }
```
I didn't realize the CRD definition itself mattered:
```yml
Name:         execpodscalers.<EPS_GROUP>
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2019-02-04T20:39:06Z
  Generation:          1
  Resource Version:    ....
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/execpodscalers.<EPS_GROUP>
  UID:                 ...
Spec:
  Group:  <EPS_GROUP>
  Names:
    Kind:       ExecPodScaler
    List Kind:  ExecPodScalerList
    Plural:     execpodscalers
    Singular:   execpodscaler
  Scope:        Namespaced
  Version:      v1
Status:
  Accepted Names:
    Kind:       ExecPodScaler
    List Kind:  ExecPodScalerList
    Plural:     execpodscalers
    Singular:   execpodscaler
  Conditions:
    Last Transition Time:  ...
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  ...
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
Events:                    <none>
```
