### ISSUE TITLE
Kubernetes was relax restrictions on environment variable names.

### ISSUE THREAD

**Issue by chenlein** [fabric8io/kubernetes-client#1361]
Reopen: #447 
[Kubernetes was relax restrictions on environment variable names.](https://github.com/kubernetes/kubernetes/pull/48986)
Sample code:
```yaml
          env:
            - name: "cluster.name"
              value: "elasticsearch-cluster-1550544058281"
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: "discovery.zen.ping.unicast.hosts"
              value: "elasticsearch-discovery-1550544058281"
            - name: "node.master"
              value: "false"
            - name: "node.data"
              value: "true"
            - name: "ES_JAVA_OPTS"
              value: "-Xms8192m -Xmx8192m"
```
Error message:
```
javax.validation.ConstraintViolationException: Constraint Validations: name must match "^[A-Za-z_][A-Za-z0-9_]*$" on bean: EnvVar(name=cluster.name, value=elasticsearch-cluster-1550544067656, valueFrom=null, additionalProperties={})
```
