### ISSUE TITLE
client.load(new FileInputStream(args[0])).createOrReplace(); throws nullPointer for "generateName"

### ISSUE THREAD

**Issue by ajaygk95** [fabric8io/kubernetes-client#1373]
If the pod-spec.yaml contains `generateName` tag then createOrReplace() is throwing the below exception.

java.lang.NullPointerException
    at java.net.URI$Parser.parse(URI.java:3042)
    at java.net.URI.<init>(URI.java:588)
    at io.fabric8.kubernetes.client.utils.URLUtils.join(URLUtils.java:48)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:208)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:177)
    at io.fabric8.kubernetes.client.handlers.PodHandler.reload(PodHandler.java:53)
    at io.fabric8.kubernetes.client.handlers.PodHandler.reload(PodHandler.java:32)
    at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:202)
    at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:62)
    at com.nokia.k8s.InterpreterLanuch.main(InterpreterLanuch.java:66)

**Comment by ajaygk95** [comment]
Discussion available in [1299](https://github.com/fabric8io/kubernetes-client/issues/1299)

**Comment by rohanKanojia** [comment]
@ajaygk95 @max5599: I'm not able to reproduce this issue. This is what I tried:
1.) Load this yaml via client and post to cluster:
```
apiVersion: v1
kind: Pod
metadata:
  generateName: zep-ag-pod
  annotations:
    kubernetes.io/psp: restricted
    spark-app-name: Zeppelin-spark-shared-process
  labels:
    app: zeppelin
    int-app-selector: shell-123
spec:
  containers:
    - name: ag-csf-zep
      image: bcmt-registry:5000/zep-spark2.2:9
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash"]
      args: ["-c","echo Hi && sleep 60 && echo Done"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
  securityContext:
    fsGroup: 2000
    runAsUser: 1510
```
2.) Code used to creating a pod:
```
      Pod aPod = client.pods().inNamespace("myproject").load(HorizontalPodAutoscaler.class.getResourceAsStream("/test-pod.yml")).get();
      client.pods().inNamespace("myproject").create(aPod);
```

After executing this, I was able to see pod being created : 
```
~/work/resouce-yamls : $ oc get pods
NAME              READY     STATUS         RESTARTS   AGE
zep-ag-podm8bfm   0/1       ErrImagePull   0          8s
```

Have I understood the bug correctly? It's about `generateName` or is it about Role?
