### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:v1#List

### ISSUE THREAD

**Issue by gastaldi** [fabric8io/kubernetes-client#1429]
Works in Kubernetes-client 4.0.7

Test case: 

```java
class SerializationTest {

    @Test
    void should_not_throw_exception() throws Exception {
        InputStream is = Files.newInputStream(Paths.get("src/test/resources/service.cache.yml"));
        assertNotNull(is);
        assertThatCode(() -> Serialization.unmarshal(is, Collections.emptyMap()))
                .doesNotThrowAnyException();
    }
}
```

service.cache.yml:

```yaml
apiVersion: v1
kind: List
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: cache-server
      labels:
        app: cache-server
    spec:
      replicas: 1
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: cache-server
        spec:
          containers:
            - env:
              - name: INFINISPAN_CONNECTORS
                value: hotrod
              image: registry.access.redhat.com/jboss-datagrid-7/datagrid73-openshift:1.0
              name: cache-server
              ports:
              - containerPort: 8778
                protocol: TCP
              - containerPort: 11211
                protocol: TCP
              - containerPort: 11222
                protocol: TCP
              - containerPort: 11333
                protocol: TCP
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: cache-server
      name: cache-server
    spec:
      selector:
        app: cache-server
      ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      - name: 8443-tcp
        port: 8443
        protocol: TCP
        targetPort: 8443
      - name: 8778-tcp
        port: 8778
        protocol: TCP
        targetPort: 8778
      - name: 11211-tcp
        port: 11211
        protocol: TCP
        targetPort: 11211
      - name: 11222-tcp
        port: 11222
        protocol: TCP
        targetPort: 11222
      - name: 11333-tcp
        port: 11333
        protocol: TCP
        targetPort: 11333
      type: ClusterIP
```
