### ISSUE TITLE
Custom Resource Definition from YAML: client.load(CRD).get() --> nullPointerException

### ISSUE THREAD

**Issue by nikkatalnikov** [fabric8io/kubernetes-client#1462]
Hello, I am using Scala and Spark-operator and getting NPE while doing:

```scala
  val client = new DefaultKubernetesClient()
  KubernetesDeserializer.registerCustomKind("sparkoperator.k8s.io/v1beta1", "SparkApplication", classOf[CustomObject])
  private val loaded = client.load(convertYamlToJson(resourceName)).get()
```

at the last line ^^

Jackson itself works fine and validates each field.

```scala
case class CustomObject @JsonCreator() (@JsonProperty("spec") spec: Spec,
                                        @JsonProperty("status") status: Option[Status]) extends CustomResource

@JsonIgnoreProperties(Array("restartPolicy"))
case class Spec @JsonCreator() (@JsonProperty("type") `type`: String,
                                @JsonProperty("mode") mode: String,
                                @JsonProperty("image") image: String,
                                @JsonProperty("imagePullPolicy") imagePullPolicy: String,
                                @JsonProperty("mainApplicationFile") mainApplicationFile: String,
                                @JsonProperty("mainClass") mainClass: String,
                                @JsonProperty("driver") driver: Driver,
                                @JsonProperty("executor") executor: Executor,
                                @JsonProperty("sparkVersion") sparkVersion: String)

case class Driver @JsonCreator() (@JsonProperty("cores") cores: Double,
                                  @JsonProperty("coreLimit") coreLimit: String,
                                  @JsonProperty("memory") memory: String,
                                  @JsonProperty("serviceAccount") serviceAccount: String,
                                  @JsonProperty("labels") labels: Labels)

case class Executor @JsonCreator() (@JsonProperty("cores") cores: Double,
                                    @JsonProperty("instances") instances: Double,
                                    @JsonProperty("memory") memory: String,
                                    @JsonProperty("labels") labels: Labels)

case class Labels @JsonCreator() (@JsonProperty("version") version: String)

case class Status @JsonCreator() (@JsonProperty("applicationState") applicationState: ApplicationState,
                                  @JsonProperty("submissionAttempts") submissionAttempts: Int,
                                  @JsonProperty("lastSubmissionAttemptTime") lastSubmissionAttemptTime: String,
                                  @JsonProperty("terminationTime") terminationTime: Option[String],
                                  @JsonProperty("sparkApplicationId") sparkApplicationId: Option[String],
                                  @JsonProperty("executionAttempts") executionAttempts: Option[Int],
                                  @JsonProperty("driverInfo") driverInfo: DriverInfo)

case class DriverInfo @JsonCreator() (@JsonProperty("podName") podName: Option[String],
                                      @JsonProperty("webUIPort") webUIPort: Option[Int],
                                      @JsonProperty("webUIServiceName") webUIServiceName: Option[String])

case class ApplicationState @JsonCreator() (@JsonProperty("state") state: String,
                                            @JsonProperty("errorMessage") errorMessage: String)
```

YAML:

```yaml
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus"
  imagePullPolicy: Always
  mainClass: consumer.KafkaConsumer
  mainApplicationFile: "http://192.168.0.104:8080/myjar.jar"
  sparkVersion: "2.4.0"
  restartPolicy:
    type: Never
  driver:
    cores: 0.1
    coreLimit: 1000m
    memory: 1024m
    labels:
      version: 2.4.0
    serviceAccount: default
  executor:
    cores: 1
    instances: 1
    memory: 1024m
    labels:
      version: 2.4.0
```

What am I doing wrong?

Stacktrace:

```
[info] it_tests.KafkaTest *** ABORTED ***
[info]   java.lang.NullPointerException:
[info]   at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.acceptVisitors(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:289)
[info]   at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:281)
[info]   at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:64)
```
