### ISSUE TITLE
Help with  Knative apiVersion

### ISSUE THREAD

**Issue by jwlai** [fabric8io/kubernetes-client#1464]
Hi, I was wondering what would be the correct way to support this Service Template Yaml?

I tried using the Client.load function to just put the YAML in. ButI ran into the issue particularly in supporting the value in the spec spec - "runLatest"

In particular it's for Knative- 

```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-java
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/{username}/helloworld-java
            env:
            - name: TARGET
              value: "Spring Boot Sample v1"
```

Thanks,
Justin Lai
