### ISSUE TITLE
Configuring ExecConfig programmatically

### ISSUE THREAD

**Issue by morganridel** [fabric8io/kubernetes-client#1517]
Hello,

I am trying to get a KubernetesClient to connect to an EKS cluster from AWS using a user of my choice. In my use case I will instantiate multiple DefaultKubernetesClient that will connect to different cluster with different user credentials.

Currently I can connect to the cluster without problem with basic code:

```java
Config config = new ConfigBuilder()
				.withMasterUrl(clusterUrl)
				.build();
		
KubernetesClient client = new DefaultKubernetesClient(config);
System.out.println(client.services().list());
```

Here is the relevant part of my config:

```
user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      env:
      - name: "AWS_ACCESS_KEY_ID"
        value: {ACCESS_KEY} #replace with real value
      - name: "AWS_SECRET_ACCESS_KEY"
        value: {SECRET_KEY} #replace with real value
      args:
      - token
      - -i
      - test-cluster
```

However I need to put the credentials inside the config file for the client to work...
 
I would like to be able to set the value of the environment when I create the client and keep it only for this client. I don't know the number of client in advance so I want to avoid creating a file per client and I can currently get the credentials in Java from an external source to use them in code.

From what I have seen the `AuthInfo` class contains an `ExecConfig` which contains the env. This env is then used in the `Config` class to fill the env inside a `Process`. If I could change the `ExecConfig` env from the config itself I think I could create different client easily.

Is there currently any way or workaround to achieve this ?

Thanks!
(This is my first issue, please tell me if you need more informations)
