### ISSUE TITLE
Mounting config map into CRD

### ISSUE THREAD

**Issue by roksolana-d** [fabric8io/kubernetes-client#1537]
I have a CRD and config map that I created. Is this possible to mount a config map into a custom object?

Here is the way I define a custom object:

  ```
  val sparkCustomResource = client.customResource(crdContext)
    sparkCustomResource.create("default", loadYaml(sparkAppFile))

    val configMapResource = client.configMaps()
      .inNamespace("default")
      .withName("app-config")

    val configMap: ConfigMap = configMapResource.createOrReplace(new ConfigMapBuilder()
      .withNewMetadata()
      .withName("app-config")
      .endMetadata()
      .addToData("application-conf", processStringFromHocon(confFilePath))
    .build())

```
The loadYaml method reads yaml file and loads it as an InputSream, processStringFromHocon method - reads application.conf file into String.

**Comment by rohanKanojia** [comment]
I haven't tried it. Are you able to do it via `kubectl`? Can you share your Custom Resource Definition so that I can see how a custom resource is mounted(it can be a list like [here](https://github.com/coreos/prometheus-operator/blob/master/example/prometheus-operator-crd/prometheus.crd.yaml#L800)?

**Comment by roksolana-d** [comment]
I did not define volume mounting in CRD as I would like to do this using library functionality.
My CRD looks like this:

```
apiVersion: sparkoperator.k8s.io/v1beta1
kind: SparkApplication
metadata:
  name: spark-mssql-job
  namespace: default
spec:
  type: Scala
  image: gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus
  imagePullPolicy: Always
  mainClass: mssql_job.SparkMssqlJob
  mainApplicationFile: jar_name.jar
  mode: cluster
  driver:
    coreLimit: 1000m
    cores: 0.1
    labels:
      version: 2.4.0
    memory: 1024m
    serviceAccount: default
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.4.0
    memory: 1024m
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.3.1.jar"
      port: 8090
```

**Comment by rohanKanojia** [comment]
I'm afraid this kind of functionality is not supported right now. Just to understand, how do you mount a configmap using `kubectl`? Does it provide some kind of mount utility that does so? I thought maybe we have to edit CR's spec in order to mount.

**Comment by roksolana-d** [comment]
I would just specify a volume to mount in a custom object definition. I do not know any other utilities to do so.

**Comment by rohanKanojia** [comment]
Sorry, It's still not so clear to me. Can you share an example with me? Maybe modified spec yaml or some link where it's shown.

**Comment by roksolana-d** [comment]
The example of config map would look like this:

```
apiVersion: sparkoperator.k8s.io/v1beta1
kind: SparkApplication
metadata:
  name: spark-mssql-job
  namespace: default
spec:
  type: Scala
  image: gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus
  imagePullPolicy: Always
  mainClass: mssql_job.SparkMssqlJob
  mainApplicationFile: local:///tmp/spark_job.jar
  mode: cluster
  driver:
    coreLimit: 1000m
    cores: 0.1
    labels:
      version: 2.4.0
    memory: 1024m
    serviceAccount: default
    volumeMounts:
      - name: app-config
        mountPath: /tmp
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.4.0
    memory: 1024m
    volumeMounts:
      - name: app-config
        mountPath: /tmp
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.3.1.jar"
      port: 8090
  volumes:
    - name: app-config
      configMap:
        name: app-conf
```
