### ISSUE TITLE
REGRESSION: Processing of OpenShift Templates with apiVersion = v1 no longer works in kubernetes-client 4.4.0

### ISSUE THREAD

**Issue by gastaldi** [fabric8io/kubernetes-client#1684]
Eg. the library is requesting the following URL when processing templates: https://dev.rdu2c.fabric8.io:8443/api/v1/namespaces/test-project-1565023015447/processedtemplates. 

In 4.3.1, it was 
https://dev.rdu2c.fabric8.io:8443/oapi/v1/namespaces/test-project-1565023127814/processedtemplates (notice the oapi in the path)

**Comment by gastaldi** [comment]
@rohanKanojia any idea what's wrong?

**Comment by gastaldi** [comment]
This is the template that fails: 

```yaml
apiVersion: v1
kind: Template
metadata:
  name: foo-template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: foo
    spec:
      ports:
        - name: foo
          port: 8443
          targetPort: 8443
      selector:
        name: foo
      type: LoadBalancer
  - apiVersion: v1
    kind: Route
    metadata:
      name: foo
    spec:
      to:
        kind: Service
        name: foo
        weight: 100
      wildcardPolicy: None
    status: {}
```


Curiously enough, this one passes (if we change the `apiVersion`):

```yaml
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: foo-template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: foo
    spec:
      ports:
        - name: foo
          port: 8443
          targetPort: 8443
      selector:
        name: foo
      type: LoadBalancer
  - apiVersion: v1
    kind: Route
    metadata:
      name: foo
    spec:
      to:
        kind: Service
        name: foo
        weight: 100
      wildcardPolicy: None
    status: {}

```
