### ISSUE TITLE
Dump Config to its kubeconfig representation

### ISSUE THREAD

**Issue by dev-dsp** [fabric8io/kubernetes-client#1741]
Hi! Is there any way to dump io.fabric8.kubernetes.client.Config as kubeconfig content?

**Comment by rohanKanojia** [comment]
try `SerializationUtils.dumpAsYaml(configObj)`

**Comment by dev-dsp** [comment]
@rohanKanojia dumpAsYaml(io.fabric8.kubernetes.api.model.HasMetadata) in SerializationUtils cannot be applied to io.fabric8.kubernetes.client.Config

**Comment by rohanKanojia** [comment]
hmm, looks like it only works for resources extending `HasMetadata`

**Comment by dev-dsp** [comment]
Found #1566 to be about the same problem, but this code won't return correct kubeconfig, it would be just yaml representation of io.fabric8.kubernetes.client.Config class:

```
import io.fabric8.kubernetes.client.Config;
import io.fabric8.kubernetes.client.internal.SerializationUtils;

            System.out.println(SerializationUtils.getMapper().writeValueAsString(Config.autoConfigure(null)));
```

**Comment by dev-dsp** [comment]
Also not clear about createNewConfig() method, which is not defined anywhere

**Comment by rohanKanojia** [comment]
@dev-dsp : What is it that is missing in generated yaml file and expected kubeconfig file? Could you please share diff if possible? that might help.

**Comment by dev-dsp** [comment]
@rohanKanojia here is what I get by running above code (removed some sensitive data):

```
requestConfig:
  username: null
  password: null
  oauthTokenProvider: null
  impersonateUsername: null
  impersonateGroups: []
  impersonateExtras: {}
  watchReconnectInterval: 1000
  watchReconnectLimit: -1
  connectionTimeout: 10000
  requestTimeout: 10000
  rollingTimeout: 900000
  scaleTimeout: 600000
  loggingInterval: 20000
  websocketTimeout: 5000
  websocketPingInterval: 1000
  maxConcurrentRequests: 64
  maxConcurrentRequestsPerHost: 5
  impersonateGroup: null
maxConcurrentRequests: 64
maxConcurrentRequestsPerHost: 5
trustCerts: false
disableHostnameVerification: false
apiVersion: "v1"
watchReconnectInterval: 1000
watchReconnectLimit: -1
connectionTimeout: 10000
requestTimeout: 10000
rollingTimeout: 900000
scaleTimeout: 600000
loggingInterval: 20000
websocketTimeout: 5000
websocketPingInterval: 1000
impersonateGroups: []
impersonateExtras: {}
tlsVersions:
- "TLS_1_2"
errorMessages:
  401: "Unauthorized! Token may have expired! Please log-in again."
```


It is YAML representation of io.fabric8.kubernetes.client.Config, and I don't see any way to convert io.fabric8.kubernetes.client.Config to io.fabric8.kubernetes.api.model.Config
