### ISSUE TITLE
Question: Can we selialize yaml to Affinity.class

### ISSUE THREAD

**Issue by TrsNium** [fabric8io/kubernetes-client#1875]
Can we selialize yaml(String) to Affinity.class?
```java
import io.fabric8.kubernetes.api.model.Affinity;
import io.fabric8.kubernetes.client.utils.Serialization;


      Affinity affinity = Serialization.unmarshal(yaml , Affinity.class);
```

**Comment by rohanKanojia** [comment]
Yes, I think it should work. Is it working in your scenario?

**Comment by TrsNium** [comment]
@rohanKanojia 
Thank you for comment!
YAML format is like following.
When serialize follwing yaml with above serialize method, returned null.
Is this normal?

```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud.google.com/gke-nodepool
          operator: In
          values:
          - "api"
```

**Comment by rohanKanojia** [comment]
hm, I don't think it's desired behavior. Could you please provide me a full testcase with which I can try to reproduce this problem?

**Comment by TrsNium** [comment]
gradle configure
```
apply plugin: 'java'
apply plugin: 'application'
mainClassName = 'testk8s.TestK8s'


repositories {
    mavenCentral()
}

dependencies {
    // kubernetes
    compile ('io.fabric8:kubernetes-client:4.6.2')
    compile "com.google.cloud:google-cloud-storage:1.90.0"
    compile "com.fasterxml.jackson.core:jackson-databind:2.10.1"
}

jar {
    manifest {
        attributes('Main-Class': 'testk8s.TestK8s')
    }
    from configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
}

```

project tree
```
.
├── bin
│   └── main
│       └── testk8s
│           └── TestK8s.class
├── build
│   ├── classes
│   │   └── java
│   │       └── main
│   │           └── testk8s
│   │               └── TestK8s.class
│   ├── generated
│   │   └── sources
│   │       └── annotationProcessor
│   │           └── java
│   │               └── main
│   ├── libs
│   │   └── test-k8s.jar
│   ├── resources
│   │   └── main
│   │       └── affinity.yaml
│   └── tmp
│       ├── compileJava
│       └── jar
│           └── MANIFEST.MF
├── build.gradle
└── src
    └── main
        ├── java
        │   └── testk8s
        │       └── TestK8s.java
        └── resources
            └── affinity.yaml
```

code
```
package testk8s;

import io.fabric8.kubernetes.api.model.Affinity;
import io.fabric8.kubernetes.client.utils.Serialization;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

public class TestK8s {
  private static final String TEST_GCS_JSON_KEY = System.getenv("TEST_GCS_JSON_KEY");

  public static void main(String[] args) throws IOException{
      File file = new File("src/main/resources/affinity.yaml");
      String affinityYamlPath = file.getAbsolutePath();
      String affinityYaml = new String(Files.readAllBytes(Paths.get(affinityYamlPath)), StandardCharsets.UTF_8);

      Affinity affinity = Serialization.unmarshal(affinityYaml , Affinity.class);
      System.out.println(affinity.getNodeAffinity());
  }
}
```
yaml
```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud.google.com/gke-nodepool
          operator: In
          values:
          - "api"
```

**Comment by TrsNium** [comment]
@rohanKanojia

**Comment by rohanKanojia** [comment]
@TrsNium : Thanks, let me try this out whenever I get time and get back to you.

**Comment by rohanKanojia** [comment]
One more thing, Could you please share your Kubernetes version on which you're trying this?

**Comment by TrsNium** [comment]
@rohanKanojia Thanks for your kind.
my kubernetes server's version is `v1.13.11-gke.14`.

**Comment by TrsNium** [comment]
project 
```
├── build.gradle
└── src
    └── main
        ├── java
        │   └── testk8s
        │       └── TestK8s.java
        └── resources
            └── affinity.yaml
```
source code 
```
package testk8s;

import io.fabric8.kubernetes.api.model.Affinity;
import io.fabric8.kubernetes.client.utils.Serialization;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

public class TestK8s {
  private static final String TEST_GCS_JSON_KEY = System.getenv("TEST_GCS_JSON_KEY");

  public static void main(String[] args) throws IOException{
      File file = new File("src/main/resources/affinity.yaml");
      String affinityYamlPath = file.getAbsolutePath();
      String affinityYaml = new String(Files.readAllBytes(Paths.get(affinityYamlPath)), StandardCharsets.UTF_8);

      Affinity affinity = Serialization.unmarshal(affinityYaml , Affinity.class);
      System.out.println(affinity.getNodeAffinity());
  }
}
```
yaml 
```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud.google.com/gke-nodepool
          operator: In
          values:
          - "api"

```

**Comment by rohanKanojia** [comment]
@TrsNium : From what I see I don't think you need to specify `affinity:` in Affinity yaml manifest. I just tried my own sample(I was preparing it when I requested a test for you). I removed it from the manifest and I was able to see Affinity being loaded correctly:
**affinity.yaml**
```
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: cloud.google.com/gke-nodepool
        operator: In
        values:
          - "api"
```
**Code used**
```
            Affinity affinity = Serialization
                    .unmarshal(AffinityLoadDemo.class.getResourceAsStream("/affinity.yml"), Affinity.class);
            System.out.println(affinity.getNodeAffinity());
```

Could you please try it out and see if it works for you? Just remove line containing `affinity:` and reformat your yaml manifest.
