### ISSUE TITLE
Cannot create a Task using the Tekton extension

### ISSUE THREAD

**Issue by jeffmaury** [fabric8io/kubernetes-client#1900]
I am trying to create a Task from this payload:

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-world1
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"

```

I always go rejected by the server and noticed that various attributes for the step are stored as additionalProperties and are lost when editing the resource.
I looked at the code and noticed that the Step model class is defined as containing a Container where it is an extension of Container (from the Go code).
