### ISSUE TITLE
How can i resolve "Message: Forbidden!Configured service account doesn't have access. "

### ISSUE THREAD

**Issue by CodingSinger** [fabric8io/kubernetes-client#1905]
i use below code to  access the k8s.
```java
    Config config = new ConfigBuilder().withNamespace(namespace).withOauthToken(token).withMasterUrl(masterUrl).build();
        LOGGER.info("K8s token:{}", token);
        this.kubernetesClient = new DefaultKubernetesClient(config);
```
And I have created ClusterRole and ClusterRoleBinding below:
```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: discovery-role
rules:
  - apiGroups: [""]
    resources: ["pods","endpoints"]
    verbs: ["list","watch","get"]

###

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: discovery-role-bind
subjects:
  - kind: ServiceAccount
    name: default
    namespace: dubbo-k8s
roleRef:
  kind: ClusterRole
  name: discovery-role
  apiGroup: rbac.authorization.k8s.io


```

but when my pod deploy in the pod within namespace `dubbo-k8s` invoke the `kubernetesClient.endpoints().inNamespace(namespace).withName(k8sService).get();` , it cause some error:

```java
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.10.10.10:6443/api/v1/namespaces/dubbo-k8s/endpoints/com-dubbo-envoy-example-demoservice. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. endpoints "com-dubbo-envoy-example-demoservice" is forbidden: User "system:serviceaccount:default:default" cannot get resource "endpoints" in API group "" in the namespace "dubbo-k8s".
```

how should i resolve this ? Thanks.
