### ISSUE TITLE
unable to create PVC : Namespace not specified. But operation requires namespace.

### ISSUE THREAD

**Issue by survivant** [fabric8io/kubernetes-client#2070]
I'm trying to run the example : PersistentVolumeClaimExample

and I replace the section that load the data from file and create them from code instead.

Here the code that I have

```
log("Creating PersistentVolumeClaim object");
        PersistentVolumeClaim persistentVolumeClaim = new PersistentVolumeClaimBuilder()
          .withNewMetadata().withName("test-pv-claim").endMetadata()
          .withNewSpec()
          .withStorageClassName("my-local-storage")
          .withAccessModes("ReadWriteOnce")
          .withNewResources()
          .addToRequests("storage", new Quantity("500Gi"))
          .endResources()
          .endSpec()
          .build();



          SerializationUtils.dumpAsYaml(persistentVolumeClaim);

        client.persistentVolumeClaims().create(persistentVolumeClaim);
```

but I received that response when I ran the code : 

Could not create resource: Namespace not specified. But operation requires namespace.

but if I take that yalm generated by : SerializationUtils.dumpAsYaml(persistentVolumeClaim);

```
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "test-pv-claim"
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "500Gi"
  storageClassName: "my-local-storage"
```

and I create that with kubectl it works fine.
