### ISSUE TITLE
Watch on CustomResource does not work if name specified

### ISSUE THREAD

**Issue by janotav** [fabric8io/kubernetes-client#2124]
I'm consistently seeing following behaviour with CRDs:

```        
CustomResourceDefinitionContext crdContext = new CustomResourceDefinitionContext.Builder()
                .withGroup("crd.com")
                .withPlural("testings")
                .withScope("Namespaced")
                .withVersion("v1")
                .build();

Watch watch = new DefaultKubernetesClient().customResource(crdContext)
                .watch("default", "test1", null, null,
                new Watcher<String>() {
                    @Override
                    public void eventReceived(Action action, String resource) {
                        LOGGER.info("Event received: " + resource);
                    }
                    @Override
                    public void onClose(KubernetesClientException cause) {
                    }
                });
```

Prints nothing, not even any http client messages. If the name is dropped from watch:

```
.watch("default", null, null, null,
```

It prints:

```
[INFO] 2020-04-09 22:18:01,952 [OkHttp https://kubernetes.docker.internal:6443/...] io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager - Websocket opened
[INFO] 2020-04-09 22:18:01,985 [OkHttp https://kubernetes.docker.internal:6443/...] oracle.aiapps.routing.example.Testing - Event received: {"apiVersion":"crd.com/v1","kind":"TestingCrd","metadata":{"creationTimestamp":"2020-04-09T19:58:15Z","generation":4,"name":"test1","namespace":"default","resourceVersion":"2264358","selfLink":"/apis/crd.com/v1/namespaces/default/testings/test1","uid":"0925177a-7555-4d68-a714-3e423785d6d2"},"spec":{"hello":"world!"}}
```
Additional details:

CRD definition:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testings.crd.com
spec:
  group: crd.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: testings
    singular: testing
    kind: TestingCrd
    shortNames: []
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            hello:
              type: string
          required:
            - hello
```

Single CRD instance existing in the cluster:

```
apiVersion: crd.com/v1
kind: TestingCrd
metadata:
  name: test1
spec:
  hello: world
```
