### ISSUE TITLE
JSONSchemaPropsOrArray does not properly serialize

### ISSUE THREAD

**Issue by bbeaudreault** [fabric8io/kubernetes-client#2153]
In https://github.com/fabric8io/kubernetes-client/pull/2151 I fixed the improper deserialization of `enum`, `default`, and `example` fields of JSONSchemaProps. During my investigation of that issue, I noticed that we also aren't properly handling JSONSchemaPropsOrArray. In that case, the bug is (so far) non-blocking because all of the necessary fields are getting picked up by the `JSONSchemaPropsOrArray#additionalProperties` field due to `@JsonAnyGetter` and `@JsonAnySetter`. 

This works in that those properties are properly re-serialized when writing to kube, but is not strictly correct for two reasons:

-  additionalProperties is a `Map<String, Object>`. As such, there is no type validation during deserialization. 
- We are erroneously including a `JSONSchemas: []` field in the resulting yaml when serializing. In my testing so far, this gets ignored by kubernetes, but that may change at any time.

In terms of correctness, this should be a `JSONSchemaProps` or `List<JSONSchemaProps>`. We should be using a custom deserializer and serializer to fill in the appropriate field based on the context (and only re-serialize the populated one), but jsonschema2pojo does not support that.

See https://github.com/nikhita/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go#L93-L120 for how they handle this in the kubernetes core. Note that they do not directly serialize the each field individually. Instead they do either/or. We could similarly do this with a `@JsonDeserialize` and `@JsonSerialize` if that were supported by jsonschema2pojo.

To visualize the problem, let's say we have a snippet of a spec like this:

```yaml
arrayA:
  type: array
  items:
    type: object
    properties:
      someKey:
        type: string
arrayB:
  type: array
  items:
    randomBadKey: "whatever we want"
    somethingElse: 123
    nestedBadness:
    - one
    - two
arrayC:
  type: array
  items:
  - type: string
  - type: integer
```

I'm going to tackle arrayA, arrayB, and arrayC separately as they all illustrate different ways this breaks down:

**arrayA**
If fabric8 were to deserialize this and reserialize, it would produce this:

```yaml
arrayA:
  JSONSchemas: []
  type: array
  items:
    type: object
    properties:
      someKey:
        type: string
```    

The JSONSchemas field should not be there. As far as I can tell, it is currently ignored by kubernetes. That may not always be the case.

**arrayB**
In this case, fabric8 would deserialize this but the value of `items` has gone totally off the rails. It no longer adheres to any open api spec. This is because additionalProperties is a `Map<String, Object>` and w should be enforcing JSONSchemaProps here instead.

**arrayC**
This syntax is both [not part of the Open API spec](https://swagger.io/docs/specification/data-models/data-types/#mixed-array) (see the bad example), and [not supported by kubernetes](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L1006-L1008). I only mention it because it is explicitly supported in the json unmarshaling, so I imagine they plan to add support in the future.

Regardless, this does not deserialize. It obviously isn't an issue that it doesn't, since it's not supported anyway. But it may be in the future so just pointing out the discrepancy.
