### ISSUE TITLE
JsonMappingException during createOrReplace()

### ISSUE THREAD

**Issue by henrikengelbrink** [fabric8io/kubernetes-client#2246]
Hello,

I'm currently trying to create the following resource with the kubernetes client with the following snippet:
```kotlin
val result = client.load(KubernetesService::class.java.getResourceAsStream("/broker.yml"))
            .inNamespace("default")
            .deletingExisting()
            .createOrReplace()
```

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: vernemq-service-1
  selfLink: /api/v1/namespaces/default/services/vernemq-service-1
spec:
  ports:
    - port: 1883
      protocol: TCP
      targetPort: 1883
  selector:
    app: vernemq-service-1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: vernemq-service-1
  name: vernemq-service-1
  selfLink: /apis/apps/v1/namespaces/default/deployments/vernemq-service-1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vernemq-service-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vernemq-service-1
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: DOCKER_VERNEMQ_ACCEPT_EULA
              value: "yes"
            - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
              value: "off"
          image: vernemq/vernemq
          imagePullPolicy: Always
          name: vernemq-service-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: getambassador.io/v2
kind:  TCPMapping
metadata:
  name:  mqtt-mapping-1
  namespace: default
spec:
  port: 1885
  service: vernemq-service-1:1883

```

Unfortunately, I'm getting the following exception:
`Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:getambassador.io/v2#TCPMapping`

The Ambassador resource is already deployed to my cluster and I'm already using it successfully. 

How can I use this TCPMapping wit the kubernetes-client ?
