### ISSUE TITLE
Version 4.10.1 trying to access "jobs" under extensions - why?

### ISSUE THREAD

**Issue by rwmajor2** [fabric8io/kubernetes-client#2300]
I am trying to use this client with a deployment in OpenShift.  As we know, extensions::jobs has been deprecated.  However, when we try to apply our YAML, I keep getting this error message:

Admin|1261|1|20|||com.arcgis.admin.site.SiteManager|Relational Datastore Module Installation Failed. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/batch/v1/namespaces/xyz/jobs/relds-aqz9m. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. jobs.extensions "relds-aqz9m" is forbidden: User "system:serviceaccount:arcgis:enterpriseadmin-serviceaccount" cannot get resource "jobs" in API group "extensions" in the namespace "xyz".

The Job YAML is using batch/v1.  Any thoughts?  Extensions::jobs does indeed _not_ exists in Openshift, but I am curious why this client is trying to check that end point.

**Comment by rohanKanojia** [comment]
Are you sure your `ServiceAccount` has correct permissions?

**Comment by rwmajor2** [comment]
This is what we have.

```
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "services"]
    verbs: ["get", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments", "replicasets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments/status"]
    verbs: ["get", "list"]
  - apiGroups: ["extensions"]
    resources: ["ingresses", "deployments"]
    verbs: ["get", "create", "update", "delete"]
  - apiGroups: ["extensions"]
    resources: ["deployments/status"]
    verbs: ["get","list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "create", "update", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["create", "update", "get", "delete"]
```
