### ISSUE TITLE
QuantityBuilder.build() will override the correct format to null 

### ISSUE THREAD

**Issue by Aitozi** [fabric8io/kubernetes-client#2343]
I upgrade kubernetes client from 4.1.0 to 4.9.2， and encounter a bug.

I want to declare a storage with 10Gi as below.

```
Quantity quantity = new QuantityBuilder()
	.withAmount("10Gi")
	.build();
```

but got only 10byte

```
resources:
  limits:
    memory: "1543503872"
    ephemeral-storage: "10"
  requests:
    memory: "1543503872"
    cpu: "10.0"
```

I think it comes from the wrong implement QuantityBuilder.build(). The setFormat will override the correct format "Gi".

```
 public Quantity build() {
        Quantity buildable = new Quantity(this.fluent.getAmount());
        buildable.setFormat(this.fluent.getFormat());
        return buildable;
    }
```

If i just use `new Quantity("10Gi")`, It will be ok .
