### ISSUE TITLE
refresh_token

### ISSUE THREAD

**Issue by sunnypatel2141** [fabric8io/kubernetes-client#2368]
I'm looking at accessing Kubernetes cluster created on IBM Cloud. In order to access the cluster, the .kube/config file has the following structure:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: <path to .pem file>
    server: <server name>
  name: <name>
contexts:
- context:
    cluster: <name>
    namespace: default
    user: <IAM user>
  name: <name>
current-context: <context>
kind: Config
preferences: {}
users:
- name: <IAM user>
  user:
    auth-provider:
      config:
        client-id: kube
        client-secret: kube
        id-token: <id_token>
        idp-issuer-url: https://iam.cloud.ibm.com/identity
        refresh-token: <refresh_token>
      name: oid
```

The current fabric8io supports providing certificate-authority and id-token in the Config:
`config.withOauthToken(value);`
`config.withCaCertFile(value) `

However, this doesn't handle the case when we require `refresh-token` in the config file in order to interact with the K8 cluster. Has someone run into this problem before? Can someone point me in the right direction ?

Thanks.
