### ISSUE TITLE
createOrReplace method doesn't support generateName for Jobs

### ISSUE THREAD

**Issue by hegdevenky** [fabric8io/kubernetes-client#2507]
`createOrReplace` method throws `java.lang.IllegalArgumentException: Name must be provided.`  when I try to create Job resource from YAML job definition file which has `generateName` property instead of `name`.  Here is my YAML definition for a Job.

```YAML
apiVersion: batch/v1
kind: Job
metadata:
 generateName: eventester
spec:
 template:
   metadata:
     name: eventester
   spec:
     containers:
     - name: eventester
       image: phx.ocir.io/ax022wvgmjpq/helloworld-oke-verifier:latest
       ports:
          - containerPort: 80
       command:
         - "/bin/bash"
         - "-c"
         - "if (( RANDOM % 2 )); then exit 0; exit 2;fi"
     restartPolicy: Never
```

Thanks,
Venky
