### ISSUE TITLE
SecretVolumeSource invalid defaultMode - needs to be sent as a string with a leading 0

### ISSUE THREAD

**Issue by dajester2013** [fabric8io/kubernetes-client#2572]
The schema for io.fabric8.kubernetes.api.model.SecretVolumeSource specifies defaultMode as "integer"

https://github.com/fabric8io/kubernetes-client/blob/ca0a124a7695b51324ab530779dbd86b735d4f94/kubernetes-model-generator/kubernetes-model-core/src/main/resources/schema/kube-schema.json#L7306

However, the API requires defaultMode to be a string with a leading zero, as indicated by this error:
```
create Pod postgres-0 in StatefulSet postgres failed error: Pod "postgres-0" is invalid: [spec.volumes[2].secret.defaultMode: Invalid value: 640: must be a number between 0 and 0777 (octal), both inclusive, spec.containers[0].volumeMounts[3].name: Not found: "cert"]
```

This is the relevant excerpt from my statefulset yaml:
```
        - name: cert
          secret: 
            secretName: postgres-cert
            defaultMode: "0640" # I even tried quoting it here...
```
