### ISSUE TITLE
How create CustomResourceDefinition object from Yaml?

### ISSUE THREAD

**Issue by sleepdan** [fabric8io/kubernetes-client#2958]
Hi!
I have a yaml file with CustomResourceDefinition: 
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.7"
      inter.broker.protocol.version: "2.7"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
``` 
how can I create the CustomResourceDefinition object correctly? 
I've tried something like this 
```java
CustomResourceDefinition customResourceDefinition = new CustomResourceDefinitionBuilder()
                .withApiVersion("kafka.strimzi.io/v1beta1")
                .withKind("Kafka")
                .withNewMetadata()
                    .withName("my-cluster")
                .endMetadata()
                .withNewSpec()
```
, but how to create the elements further?:
 ```yaml
 kafka:
    version: 2.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.7"
      inter.broker.protocol.version: "2.7"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {} 
```
Maybe there is some similar example?
