### ISSUE TITLE
crd-generation: field annotated with @PrinterColumn of type enum defined as object in the genrated CRD 

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/kubernetes-client#3011]
If a field of a CR is an enum and annotated with `@PrinterColumn`, the resulting CRD definition reports it as an `object` which is invalid.

```yaml
additionalPrinterColumns:
  - JSONPath: .status.phase
    name: PHASE
    type: object
```

kubernetes-client: 5.3.0
reproducer: https://github.com/lburgazzoli/fabric8-kubernetes-client-crdgen
