### ISSUE TITLE
Incorrect validation of status field when creating Crd

### ISSUE THREAD

**Issue by JeffreyThijs** [fabric8io/kubernetes-client#3012]
When creating a crd, I encountered an issue where the status field was invalidated incorrectly resulting in the failure of creating the resource. The status field is configured to be null although an exception is returned that the object type is invalid. A temporary solution is to exclude the status field to be serialized by using the following annotation: `@JsonIgnoreProperties(value = { "status" })` which results in a successful post. The encountered error message and a brief form of the used code can be found below.

Error log:

Exception during creating of resource: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://xxx.xxx/apis/abc.def/v1beta1/namespaces/test/resources. Message: Resource.abc.def "testresource" is invalid: status: Invalid value: "null": status in body must be of type object: "null". Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=status, message=Invalid value: "null": status in body must be of type object: "null", reason=FieldValueInvalid, additionalProperties={})], group=abc.def, kind=Resource, name=testresource, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Resource.abc.def "testresource" is invalid: status: Invalid value: "null": status in body must be of type object: "null", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).

Used code:

Resource:

```java
@Version(ResourceCrd.VERSION)
@Group(ResourceCrd.GROUP)
@Kind(ResourceCrd.KIND)
// @JsonIgnoreProperties(value = { "status" })  // NOTE: uncomment this to solve the issue
public class ResourceCrd extends CustomResource<ResourceCrdSpec, Void> implements Namespaced {

    public static final String KIND = "Resource";
    public static final String GROUP = "abc.def";
    public static final String VERSION = "v1beta1";

    public ResourceCrd() {}

    public ResourceCrd(final String name) {
        final ObjectMeta metadata = new ObjectMeta();
        metadata.setName(name);
        setMetadata(metadata);
        setSpec(new ResourceCrdSpec(name));
    }
}
```

Spec:

```java
@JsonDeserialize(using = JsonDeserializer.None.class)
public class ResourceCrdSpec implements KubernetesResource {

    public String name;

    public ResourceCrdSpec() {
    }

    public ResourceCrdSpec(final String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }
}
```
List:

```java
public class ResourceCrdList extends CustomResourceList<ResourceCrd> {
}

```

Repo:

```java
@ApplicationScoped
public class ResourceCrdRepository {

    private KubernetesClient _kubernetesClient;
    private final Logger _logger = Logger.getLogger(getClass());
    private final NonNamespaceOperation<ResourceCrdSpec, ResourceCrdList, Resource<ResourceCrd>> _client;

    @Inject
    public ResourceCrdRepository(final KubernetesClient kubernetesClient) {
        _kubernetesClient = kubernetesClient;

        KubernetesDeserializer.registerCustomKind(
            HasMetadata.getApiVersion(ResourceCrd.class),
            HasMetadata.getKind(ResourceCrd.class),
            ResourceCrd.class
        );
        _client =
            _kubernetesClient
                .customResources(ResourceCrd.class, ResourceCrdList.class)
                .inNamespace("test");
    }

    public void createResource(final String name) {
        try {
            _client.create(resource);
        } catch (final Exception e) {
            _logger.error("Exception during creating of resource", e);
        }
    }
}
```

**Comment by metacosm** [comment]
Which version of the client are you using?

**Comment by JeffreyThijs** [comment]
@metacosm, 5.3.0.

**Comment by metacosm** [comment]
@JeffreyThijs and to make sure, you generated the CRD using the CRD generator, applied it to your cluster and then tried to create CRs based on it, correct?

**Comment by JeffreyThijs** [comment]
@metacosm, the CRD was created manually and applied to the cluster. The used definition:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resources.abc.def
spec:
  group: abc.def
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
  scope: Namespaced
  names:
    plural: resources
    singular: resource
    kind: Resource
```
