### ISSUE TITLE
[crd-generator] Map properties lack additionalProperties

### ISSUE THREAD

**Issue by clement-buchart** [fabric8io/kubernetes-client#3041]
Hello,

I've been migrating some internal operator from the go-based CRD generation to the Java based one. Thanks for this lib.

One issue I had during the migration is that when a Spec Pojo has a Map property (in my case Map<String, String>), the generated property in the schema is of `type: object` but has no `additionalProperties` field.

Example property 
```
    private Map<String, String> deploymentProperties;
```

When using using the Go generator, the generated schema is
```
            deploymentProperties:
              additionalProperties:
                type: string
              type: object
```
When using using the Java based generator, the schema is
```
                deploymentProperties:
                  type: object
```

This make Kubernetes reject my CustomResource when the map is not empty.

My current workaround is 
```
yq e '.spec.versions.[].schema.openAPIV3Schema.properties.spec.properties.deploymentProperties |= ( . * {"additionalProperties" : {"type" : "string"}})' customresource.yaml
```
