### ISSUE TITLE
Helm Openshift client API support and documentation

### ISSUE THREAD

**Issue by aditya22-intel** [fabric8io/kubernetes-client#3077]
Please provide support to install helm chart in Openshift 
Few examples as to how we can use helm classes to deploy helm chart on Openshift
Also, the documentation doesn't talk about the code implementation through java or any other programing language

**Comment by rohanKanojia** [comment]
I don't understand. As far as I know this repository has nothing to do with helm

**Comment by manusa** [comment]
In OpenShift 4 you can crate an application from a Helm Chart.

![image](https://user-images.githubusercontent.com/488391/117099614-e7650880-ad71-11eb-825c-882413e8cae1.png)

I'm not sure if this part of the webconsole maps to this, but there is a CRD group for Helm `helm.openshift.io` with at least a `helmchartrepositories.helm.openshift.io` where you can define your own Helm reporisotires:

```yaml
kind: HelmChartRepository
apiVersion: helm.openshift.io/v1beta1
# ....
spec:
  connectionConfig:
    url: https://redhat-developer.github.io/redhat-helm-charts
  name: Red Hat Helm Charts
```


However, besides the Helm catalog handling (which I'm yet unsure maps to this CRD), I'm not sure if there's some other way to request a deployment from a Helm chart besides the webconsole.
