### ISSUE TITLE
Generated crd has a validation error

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3082]
With crd-generator 5.2.1 my installed generated crd is reporting:

```
conditions:
  - lastTransitionTime: "2021-05-06T14:56:48Z"
    message: 'spec.preserveUnknownFields: Invalid value: true: must be false'
    reason: Violations
    status: "True"
    type: NonStructuralSchema
```

There's nothing on the custom resource class nor in the generated yml that mentions preserveUnknownFields.

cc @metacosm
