### ISSUE TITLE
System Namespaces 

### ISSUE THREAD

**Issue by thomasdevos69** [fabric8io/kubernetes-client#3161]
Hello,

This is just a query / no issue. 

How can I recognise a system namespace i.e. kube-system. using Fabric?

Thanks
Thomas

**Comment by rohanKanojia** [comment]
I'm not able to see any difference in namespaces created by system and namespaces created by users. Is it possible for you to add `system=true` label in system namespaces like `kube-system`, `kube-public`?
```yaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2021-05-10T09:56:02Z"
  labels:
    system: "true"
  name: kube-public
```
Then you might be able to list like this:
```java
try (KubernetesClient client = new DefaultKubernetesClient()) {
  NamespaceList systemNamespaceList = client.namespaces().withLabel("system", "true").list();
}
```
