### ISSUE TITLE
io.fabric8.kubernetes.api.model.apiextensions.v1.JSONSchemaProps does not retain extensions

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/kubernetes-client#3182]
i.e. there's no way to get the value of `x-descriptors`

```yaml
  accessKey:
    title: Access Key
    description: The access key obtained from AWS
    type: string
    format: password
    x-descriptors:
    - urn:alm:descriptor:com.tectonic.ui:password
```

Looking at the `JSONSchemaProps` class, it looks like it handle a [specific set of json extensions](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-model-generator/kubernetes-model-apiextensions/src/generated/java/io/fabric8/kubernetes/api/model/apiextensions/v1/JSONSchemaProps.java#L172-L184).

Would be nice to have a generic support for extensions.
