### ISSUE TITLE
[Question] Why parsing yaml to the resource duplicates kind property?

### ISSUE THREAD

**Issue by sknot-rh** [fabric8io/kubernetes-client#3195]
Hi.
I am using the vsion 5.4.0.I have a custom resource defined as 
```
public class MyResource extends CustomResource<MyResourceSpec, MyResourceStatus> implements Namespaced, UnknownPropertyPreserving { ... }
```
In my test, I am trying to parse yaml into the object of this class. So I am doing similar
```
class TestClass<T extends HasMetadata,
        L extends KubernetesResource & KubernetesResourceList,
        R extends Resource<T>> {

    protected T copyResource(T resource) {
            ObjectMapper objectMapper = new ObjectMapper();
            try {
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                objectMapper.writeValue(baos, resource);
                return (T) objectMapper.readValue(baos.toByteArray(), resource.getClass());
            } catch (IOException e) {
                return null;
            }
    }
}
```
However, the mapper writes an object with a duplicate `kind` property. For example: 
```
---
apiVersion: "my.org/v1alpha1"
kind: "MyResource"
metadata:
  name: "my-resouce"
  namespace: "default"
spec:
  property: value
kind: "MyResource"
```
I think kubernetes API does cope with duplicities in the resource yaml, however I do have issues in my test suite. Do you have any idea what has been changed in this regard? The version of jackson has not changed, so it has to be something about `CustomResource` class. Thank you
