### ISSUE TITLE
KubernetesMockServer mixes CRD for list requests

### ISSUE THREAD

**Issue by Fabian-K** [fabric8io/kubernetes-client#3216]
Hi,

when there are multiple CRD with the same kind but from different groups, the mock server will mix those for list requests.

```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
```

If you create an instance of Tekton Trigger and then list all Knative Triggers, it will return the Tekton Trigger. Looks like this is because the KubernetesAttributesExtractor only extracts the kind as an attribute and ignores apiVersion.

https://github.com/fabric8io/kubernetes-client/blob/1c942a086cf775e02de1211e220fce8ad99dd5b3/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java#L173-L177

Thanks, Fabian
