### ISSUE TITLE
Add support for client-side dry runs

### ISSUE THREAD

**Issue by gewei2000** [fabric8io/kubernetes-client#3259]
Add support for client-side dry runs when operate resources.
 
An example with kubectl:

```
kubectl create namespace xxx --dry-run=client
```

**Comment by manusa** [comment]
I'm not sure how'd you'd expect this to work.

From `kubectl` perspective it's easy because it changes the behavior of the CLI to print the YAML that is sent to the server.

However, from a Java client library, I don't know what'd the expected output of that invocation would be. I would only understand this in the terms of an extra method `clientDryRun()` that would return an instance of `T`  for Createable operations.

As stated, for kubectl this might make sense because some resources are computed for some operations (such as `create namespace`). But in terms of our client, in most cases, the object that is sent to the server is the same unmodified version that's passed as an Item argument to the `create` method.

Would you elaborate on what are your expectations for this feature?

**Comment by gewei2000** [comment]
@manusa I want to get the same server error, such as mismatched namespace or incorrect label selector

```
command: kubectl create --namespace="demo-ns" --dry-run=client -f nginx.yaml
error: the namespace from the provided object "demo" does not match the namespace "demo-ns". You must pass '--namespace=demo' to perform this operation
```

yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: demo
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app-name: nginx
    spec:
      containers:
        - name: nginx
          imagePullPolicy: IfNotPresent
          image: nginx:latest
```
