### ISSUE TITLE
Serialization unmarshal: wrong resources limit parsing

### ISSUE THREAD

**Issue by aleboulanger** [fabric8io/kubernetes-client#3353]
> with the 5.3.1 version 

The values from the limits resources definition are double quoted even if I already put a quote on it

for example:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: XXXX
spec:
  template:
    spec:
      containers:
          command:
            - /bin/sh
          image: XXXX
          name: XXXX
          resources:
            limits:
              cpu:
                amount: '2'
                format: ''
              memory:
                amount: '1'
                format: 'Gi'
            requests:
              cpu:
                amount: '1'
                format: ''
              memory:
                amount: '1'
                format: 'Gi'
```

with the java client:

```java
Job job = Serialization.unmarshal(K8sClientTest.class.getResourceAsStream("job.yaml"), Job.class);
System.out.println(Serialization.asYaml(job))
```

I will have values like 

```yaml
        resources:
          limits:
            cpu: "\"2\"\"\""
            memory: "\"1\"\"Gi\""
          requests:
            cpu: "\"1\"\"\""
            memory: "\"1\"\"Gi\"]"
```

instead of 

```yaml
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
```

**Comment by aleboulanger** [comment]
don't have the issue with this kind of definition

```yaml
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
```
