### ISSUE TITLE
How to approve csr?

### ISSUE THREAD

**Issue by pananqi** [fabric8io/kubernetes-client#3406]
Hi,

May I know how to approve/reject the CertificateSigningRequest?
FYI, I was able to create the CSR with the sample below
https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#certificatesigningrequest

But I didn't find any api that implements 'kubectl certificate approve <certificate-signing-request-name>',
appreciate your advice on this, thank you.

Regards,
TK

**Comment by rohanKanojia** [comment]
Looks like for`kubectl certificate approve` client hits an additional subresource endpoint:
```
PUT https://127.0.0.1:35187/apis/certificates.k8s.io/v1/certificatesigningrequests/myuser/approval
```
We don't seem to support this `/approval` endpoint. I see this updates the status of CSR:
```yaml
status:
  certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5ekNDQWQrZ0F3SUJBZ0lSQUtObFpEQWJaYVcxelZZOFFFYVhESnN3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TVRBNE1UWXhNVEV3TWpaYUZ3MHlNakE0TVRZeApNVEV3TWpaYU1CRXhEekFOQmdOVkJBTVRCbUZ1WjJWc1lUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFOSzdQQ0M3UnJ1dFl5NzdjVlROa1ZVMWROeG1VVW1KZUxvcDFJL0F5R1dkRGJiOVJaaEUKRWNMb1loWmZFTjZvclFadE5RRWRnaUZLUmNIN0Nlc2Rhc0t3YkZSMkpZZ09WNlJHV042dGFaTkIrTjc4SVczdgptZXRVcEU2c2lEMTBDL2pIUFRrcFo1dGFBNyt3cGlSVE5TQ3hFZXdPUlg3eWZCaEJkczdhWVlpQk41NkZwcmJHCktLNXpwZDdJaGdueFlPTVg0TWNxTnA0b01VbE15THBySUZhRHQ1SmppN2hFTTZzM1l3Y0MwVnBvZ3lIOWFTMmMKOW8xSUkxc1VSd2QxOW1ibEZscmpqam44MXR6Q29UdHBhdjMvd3J2OUd6dTdDN2RQc0VueXlEcmkxcXFMWjFaaApaUzkvb3p2K2w5d3Z0QXc4dllpcVpxM0U5SUYzeXMydWJhMENBd0VBQWFOR01FUXdFd1lEVlIwbEJBd3dDZ1lJCkt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JUWUpiVEE5UmxEaTRZZFZQVk4KZEw1WGpIVEI3REFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBaFhIOXJnc3lodUpqWWRwWHNpd2lWZFBibG5pawpBem5zckYzR21CeEFCY1V4c3U0RVVSekZ1VjZOdk9ZbFEwT2NCZ0k3RXNWMUkvYlNxb3BZN2tvSHBLQm51RW9ICnp6ZHlqcXJ6UGx0dmdMb1EzdnA2YlZOOFUxSE52T2lVNVVsYW9GKzk1cmdjcEsrV2orWTZVMDRLZXVJaXg0SzMKYVJJZ2NyVUFhVUZtQVhwbTlORWhVM3hBRXRYVVZwVVdVa0s2dTBHTysvZlhHSnh1UXFmR2l2Z2FMNXZ1RVVwaApublhIRWlGTE8rZ2plSVFTQnJhZ3E0T2t1OHhtS0wxYWdnK3dwQmRjQXBqdVF4VndtTUxXeit5N0R5d2JYZUJoCmJma0ZUVnZtM2hGY21iVVRJSUR0RGV1TmpQNWxtdVRzSzhGZzBBQWNacHp4UDBmc3pEcGxzcHNxcHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  conditions:
  - lastTransitionTime: "2021-08-16T11:15:26Z"
    lastUpdateTime: "2021-08-16T11:15:26Z"
    message: This CSR was approved by kubectl certificate approve.
    reason: KubectlApprove
    status: "True"
    type: Approved
```

Does it work when you try to update status using `updateStatus()` call?
