### ISSUE TITLE
Allow to specify POJO enum values for the corresponding generated CRD enum

### ISSUE THREAD

**Issue by ppatierno** [fabric8io/kubernetes-client#3411]
When a POJO contains an enum, I would like to serialize it into the corresponding CRD with a specific name instead of the field one.
For example, if an enum is defined this way:

```java
public enum MyEnum {
       Foo,
       Bar,
```

The corresponding CRD will be the following:

```yaml
name:
    enum:
    - Foo
    - Bar
    type: string
```

while I would like to have:

```yaml
name:
    enum:
    - foo
    - bar
    type: string
```

or anyway any other name (i.e. if for any crazy reason I want `Foo` to be `aaa` in the CRD).
I tried the `JsonProperty("foo")` on the enum but with no luck.
