### ISSUE TITLE
NamespacedKubernetesClient createOrReplace() not being able to fetch CRD details

### ISSUE THREAD

**Issue by tacf** [fabric8io/kubernetes-client#3555]
Hi,

I've bumped into an issue where i'm unable to understand if this is happening due to misunderstanding of the library of actually an issue.

The basic gist is that i'm trying to apply a manifest which has two objects (service and a custom object - a vault controller object) and from debugging it seems that the code flow reach a point where the operation of finding the handler of the object is being executed without being supplied a proper client which in turn makes it not able to return a proper handler.

The call being done is 

```kotlin
client.load(ByteArrayInputStream(manifest.toByteArray(Charsets.UTF_8)))
                    .createOrReplace()
```
where the client is actually a `NamespacedKubernetesClient`

and the partial stack trace (omitting code up until the call above) where is happens is bellow

```
get:68, Handlers (io.fabric8.kubernetes.client)
handlerOf:260, NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl (io.fabric8.kubernetes.client.dsl.internal)
acceptVisitors:246, NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl (io.fabric8.kubernetes.client.dsl.internal)
lambda$getItems$1:86, NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl (io.fabric8.kubernetes.client.dsl.internal)
apply:-1, 728226897 (io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl$$Lambda$1569)
accept:195, ReferencePipeline$3$1 (java.util.stream)
forEachRemaining:1655, ArrayList$ArrayListSpliterator (java.util)
copyInto:484, AbstractPipeline (java.util.stream)
wrapAndCopyInto:474, AbstractPipeline (java.util.stream)
evaluateSequential:913, ReduceOps$ReduceOp (java.util.stream)
evaluate:234, AbstractPipeline (java.util.stream)
collect:578, ReferencePipeline (java.util.stream)
getItems:88, NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl (io.fabric8.kubernetes.client.dsl.internal)
getOperations:92, NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl (io.fabric8.kubernetes.client.dsl.internal)
createOrReplace:172, NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl (io.fabric8.kubernetes.client.dsl.internal)
createOrReplace:53, NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl (io.fabric8.kubernetes.client.dsl.internal)
```

Any help would be appreciated.

**Comment by manusa** [comment]
Could  you provide the content of you manifest?

**Comment by tacf** [comment]
Here's the somewhat redacted manifest

```yaml
---
apiVersion: vaultproject.io/v1
kind: SecretClaim
metadata:
  name: mysecretclaim
  namespace: mynamespace
spec:
  type: Opaque
  path: secret/app/path/to/my/secret
  renew: 3600
---
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
  namespace: mynamespace
  labels:
    label1: value1
    label2: value2
  annotations:
    author: someone@email.ocm
spec:
  ttlSecondsAfterFinished: 1
  backoffLimit: 0
  template:
    metadata:
      namespace: mynamesapec
      labels:
        label1: v1
        label2: v2
        label3: v3
        label4: v4
        label5: v5
      annotations:
        vault.security.banzaicloud.io/vault-role: myvaultrole
        vault.security.banzaicloud.io/vault-env-daemon: 'true'
    spec:
      containers:
      - name: myappcontainer
        image: internal.registry.com/myappimage:version1234
        command:
        - java
        - -jar
        - myjar.jar
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 256Mi
        env:
        - name: VAR1
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ENV_VAR_1
          value: value
      restartPolicy: Never
```

and the CRD related with the first object (which is already applied when applying the manifset)

```yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations: {}
  name: secretclaims.vaultproject.io
spec:
  group: vaultproject.io
  names:
    kind: SecretClaim
    plural: secretclaims
    singular: secretclaim
  scope: Namespaced
  version: v1
```

Following the trace above you'll find that the flow follows a code path where the K8s client is set at some point to null (by not being passed any client to the function being called) this is actually what confuses me a bit in this case. Hence me wanting to understand if i'm misusing the library for some reason.
