### ISSUE TITLE
CRD generator emit an incorrect signature for Maps

### ISSUE THREAD

**Issue by andreaTP** [fabric8io/kubernetes-client#3679]
### Describe the bug

Having a Java object that define a `Map` property such as:

```java
    private java.util.Map<String, java.util.List<String>> test = null;

    public java.util.Map<String, java.util.List<String>> getTest() {
        return test;
    }
```

The crd-generator emits:

```yaml
              test:
                additionalProperties:
                  type: string
                type: object
```

This signature force the user to create corresponding CRs like the following:

```yaml
  test:
    key1: "value1"
```

But, trying to read it back from Kubernetes using the client fails with the following exception:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('value1')
```

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

- Create a Java object containing a Map field
- Generate the corresponding CRD
- Create a CR for the generated CRD
- `kubectl apply -f` the created resources
- try to read the CR with the kubernetes-client e.g.:

```java
kc.customResources(YourClass.class).list().getItems().get(0)
```

### Expected behavior

The generated CRD should respect the type signature of the field generating this yaml instead:

```yaml
                test:
                  additionalProperties:
                    type: array
                    items:
                      type: string
```

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Kubernetes API Server version

1.22.3@latest

### Environment

other (please specify in additional context)
