### ISSUE TITLE
CRD generator doesn't handle correctly JsonNode type

### ISSUE THREAD

**Issue by andreaTP** [fabric8io/kubernetes-client#3683]
### Describe the bug

The CRD generator produce an empty object for fields with type `JsonNode`.

### Fabric8 Kubernetes Client version

next (development version)

### Steps to reproduce

Generate the CRD for a class containing a field like:

```java
public JsonNode configuration;
```

the output is:

```yaml
              configuration:
                type: object
```

### Expected behavior

the expected output should be:

```yaml
              configuration:
                type: object
                x-kubernetes-preserve-unknown-fields: true
```

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Kubernetes API Server version

1.22.3@latest

### Environment

other (please specify in additional context)
