### ISSUE TITLE
[crd-gen] Possibility to add a description to Array/Map "items"

### ISSUE THREAD

**Issue by andreaTP** [fabric8io/kubernetes-client#3767]
### Is your enhancement related to a problem? Please describe

It's common practice (e.g. using `kubebuilder`) to add a specific description on the `items` of `array`s.
E.g.:

```yaml
my-field:
  description: Generic field description
  items:
    description: Specific item description
    properties:
       ...
  type: array
  ```
  
Currently the CRD generator infer the description from a field annotated with `JsonPropertyDescription`, unfortunately this covers only the `Generic field description` from the example and we don't have a way to express the `Specific item description` from above.

### Describe the solution you'd like

We should be able to define Array/Maps etc. `items` description.

A possibility is to add a new specific `Annotation` for this use-case, possibly making it flexible enough to be able to add a `description` field anywhere is allowed in the CRD.

### Additional context

cc. @metacosm
