### ISSUE TITLE
[crd-gen] Possibility to add extra information to fields

### ISSUE THREAD

**Issue by andreaTP** [fabric8io/kubernetes-client#3768]
### Is your enhancement related to a problem? Please describe

The most self-explanatory example is the type format hint allowed in the CRD such as:

```yaml
weight:
  description: weight associated with matching
    the corresponding podAffinityTerm, in the
    range 1-100.
  format: int32
  type: integer
```

Currently the generator emits only the `type` information and we don't have, at best of my knowledge, any way to express a specific `format`.

I'm opening this ticket more widely in the hope that we can agree on a solution that will cover additional use-cases:
- `x-kubernetes-list-type`
- `pattern`
- `format`
- `default`
- `nullable`
- ...

but I'm open to evaluate specific solutions (e.g. one per missing property).

### Describe the solution you'd like

A possible solution, again, is a new custom annotation, even if some of those fields might be extracted more automagically by the generator (e.g. `nullable` and `default`).

### Additional context

cc. @metacosm
