### ISSUE TITLE
How to check the name of the current deployment within operator?

### ISSUE THREAD

**Issue by FuyaoLi2017** [fabric8io/kubernetes-client#3837]
Hello Community,
I am writing a Fabric8io based k8s operator. I want to know inside the operator code, how to inspect the name of the deployment this operator is sitting in. This could be dynamic since I use helm chart. Thanks.

**Comment by manusa** [comment]
You can easily expose the `Pod` name (and other fields) as an [environment variable](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/) and then work your way up from there:

In your `Deployment`, you can add the following to the `Pod` template:

```yaml
spec:
  template:
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
    
```

With this, you can now retrieve the `Pod` info from the kube api (`client.pods().inNamespace(namespace).withName(name).get()`)

This will provide you with the owner references (in your case should be a `ReplicaSet`). With this info you can retrieve the `ReplicaSet`, and follow the same procedure to get to the `Deployment`.

A similar approach can be achieved using [files](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/) instead of environment variables.
