### ISSUE TITLE
[java-gen] Support Min/Max/Pattern javax.validation.constraints

### ISSUE THREAD

**Issue by OneCricketeer** [fabric8io/kubernetes-client#3870]
### Is your enhancement related to a problem? Please describe

I noticed that `required` fields get a `@NotNull` annotation applied, but there are other supported validation patterns that can be applied to generated Java models as well

https://javaee.github.io/tutorial/bean-validation002.html

### Describe the solution you'd like

Examples

https://github.com/fabric8io/kubernetes-client/blob/1d7d869681faafe166e5581bcde0f928499ef765/java-generator/core/src/test/resources/akka-microservices-crd.yml#L48-L49

Mapped to

```java
@Min(0)
@Max(1000)
```

https://github.com/fabric8io/kubernetes-client/blob/1d7d869681faafe166e5581bcde0f928499ef765/java-generator/core/src/test/resources/akka-microservices-crd.yml#L75-L76

Mapped to

```java
@Pattern(...)
```

### Describe alternatives you've considered

Manually adding these where they would be needed. 

### Additional context

The objects will fail to be constructed if an invalid value is provided when the annotations are present. 

Use-case: Preventing bad user-provided input fields into an API layer.

**Comment by andreaTP** [comment]
Pretty confident they will come soon (I have some POCs for this already).

**Comment by leoandrea7** [comment]
Hi, any news about this annotations support?

**Comment by andreaTP** [comment]
Hi @leoandrea7 , this is not supported yet, although it might be relatively straightforward to implement it.

Let's see if @fabiobrz gets intrigued enough 😏 , but, in general, would you mind sharing your use case?

**Comment by leoandrea7** [comment]
I have a CRD with openAPIV3Schema like this:
```
....
    kafka:
      type: object
      properties:
        port:
          type: integer
          minimum: 0
          maximum: 65535
          nullable: false
        hostname:
          type: string
          pattern: '^([A-Za-z0-9-]{1,63}\.)+[[A-Za-z0-9-]{1,63}$'
          nullable: false
      nullable: false
.....
```
The problem is that crd-generator does not generate the fields minimum, maximum and pattern.
I see that nullable will be introduced in the next release.  [Issue-3975](https://github.com/fabric8io/kubernetes-client/issues/3975)

Thanks a lot @andreaTP!
