### ISSUE TITLE
From "Running" to "Terminating", only 2 second ~

### ISSUE THREAD

**Issue by ZhangTianCi** [fabric8io/kubernetes-client#4000]
### Describe the bug

Use api to create a job.
when pod "Running" ,2 second later, the pod status while change to "Terminating".

But,when i use kubectl create -f file.yml . all is ok.

```
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>4.10.1</version>
        </dependency>
```

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

```
kubernetesClient.batch().jobs().inNamespace(namespace).create(job);
```

### Expected behavior

right to create job.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

**Comment by ZhangTianCi** [comment]
```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-3-24-1
spec:
  template:
    metadata:
        name: test-3-24-1
    spec: 
      restartPolicy: OnFailure
      containers:  
      - name: test-3-24-1
        image: 192.168.0.1/image:1.0.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - ' echo export SOURCE=$(curl http://127.0.0.1:8080/get) >> /etc/profile'
        env:
          - name: engineType
            value: jmeter
          - name: confPath
            value: /etc/engine/config/engine.conf
          - name: engineLogPath
            value: /etc/engine/script/25/46
        command: ["sh", "-c", "sh /start.sh"] 
        resources:
          requests:
            cpu: 2
            memory: 2500Mi
          limits:
            cpu: 2
            memory: 2500Mi
        terminationMessagePath: /etc/engine/script/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: use-file       
          mountPath: /etc/engine/script/
          readOnly: false  
      volumes: 
      - name: use-file
        nfs: 
          server: 192.168.1.109
          path: /data/store
```
