### ISSUE TITLE
list create fails for DeploymentList

### ISSUE THREAD

**Issue by ravilr** [fabric8io/kubernetes-client#412]
@jimmidyson @iocanel 

KubernetesList list = client.inNamespace(namespace).lists().load(is).get();
client.inNamespace(namespace).lists().create(list);

where the inputStream has:
$ cat nginx-deployment.yaml 
```
apiVersion: extensions/v1beta1 
kind: DeploymentList
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: nginx-deployment
    annotations: 
      k8s.starfleet.io/version: "1"
  spec:
    replicas: 3
    revisionHistoryLimit: 1
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
          - containerPort: 80
```
results in:
Caused by: java.lang.IllegalStateException: Could not find handler
        at io.fabric8.kubernetes.client.dsl.internal.KubernetesListOperationsImpl.create(KubernetesListOperationsImpl.java:117) ~[kubernetes-client-1.3.83.jar:na]
        at io.fabric8.kubernetes.client.dsl.internal.KubernetesListOperationsImpl.create(KubernetesListOperationsImpl.java:78) ~[kubernetes-client-1.3.83.jar:na]
        at io.fabric8.kubernetes.client.dsl.internal.KubernetesListOperationsImpl.create(KubernetesListOperationsImpl.java:43) ~[kubernetes-client-1.3.83.jar:na]
