### ISSUE TITLE
scaling down a deployment resource to 0 never returns

### ISSUE THREAD

**Issue by ravilr** [fabric8io/kubernetes-client#418]
@jimmidyson 

looks like there is some issue with scaling down a deployment to 0.  the underlying Replicaset resource itself is scaled down to 0 and the pods are getting deleted. but, it waits on waitUntilDeploymentIsScaled forever..

at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.waitUntilDeploymentIsScaled(DeploymentOperationsImpl.java:92)
at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.scale(DeploymentOperationsImpl.java:62)
at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.scale(DeploymentOperationsImpl.java:39)

**Comment by ravilr** [comment]
It seems the deployment controller manager doesn't write all the fields in deploymentStatus object, after scaling down to 0. i see only observedGeneration, but no replicas/updatedReplicas/availableReplicas fields.

stripped down output of `kubectl get deployment -o yaml` after scale down to 0.
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  .......
  generation: 8
......
spec:
  minReadySeconds: 30
  replicas: 0
.........
status:
  observedGeneration: 8
```
