### ISSUE TITLE
[crd-gen] Support openAPIV3Schema fields: minimum, maximum, pattern, nullable

### ISSUE THREAD

**Issue by leoandrea7** [fabric8io/kubernetes-client#4224]
### Is your enhancement related to a problem? Please describe

_(duplicate of #2959)_

At the moment there is no way to auto generate a crd (with crd-gen tool) that contains properties with validation fields like **_minimum_**, **_maximum_**, **_pattern_**, **_nullable_**.

CRD example:

```yaml
...

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.example.com
spec:
  group: example.com
  names:
    kind: Tenant
    plural: tenants
    singular: tenant
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              kafka:
                type: object
                properties:
                  port:
                    type: integer
                    minimum: 0
                    maximum: 65535
                    nullable: false
                  hostname:
                    type: string
                    pattern: '^([A-Za-z0-9-]{1,63}\.)+[[A-Za-z0-9-]{1,63}$'
                    nullable: false
                nullable: false
...
```

### Describe the solution you'd like

I'd like to use javax annotation (like `@min @max @pattern`) on a java model fields.

    private String protocol;

    @Pattern(regexp = "\\^\\(\\[A-Za-z0-9-]\\{1,63}\\\\\\.\\)\\+\\[\\[A-Za-z0-9-]\\{1,63}\\$")
    private String hostname;

    @Min(0)
    @Max(65535)
    private Integer port;

Currently @NotNull annotation generate the filed "**_required_**" on crd, but for "_**nullable**_" validation maybe we need of a new specific annotation.

### Additional context

version: 5.12.2
