### ISSUE TITLE
[crd-gen] Enum fields written in generated crd yaml 

### ISSUE THREAD

**Issue by leoandrea7** [fabric8io/kubernetes-client#4225]
### Describe the bug

When the crd-gen tool tries to generate schema properties from an enum, both values and fields are written in the generated crd yaml.

### Fabric8 Kubernetes Client version

5.12.2

### Steps to reproduce

Create an enum with values and at least a field and put it into Spec. 
Example:

```
@Group("com.example")
@Version("mycrd")
@Plural("mycrds")
public class MyCRD extends CustomResource<MyCRDSpec, Void> implements Namespaced {

  public class MyCRDSpec {

    private Test test;

    public enum Test {
      A("test-a"),
      B("test-b");

      private final String field1;

      Test(String field1) {
        this.field1 = field1;
      }

      public String getField1() {
        return field1;
      }
    }
  }
}


```

Exec `mvn clean compile`

the generated file target/classes/META-INF/fabric8/mycrds.com.example-v1.yml will contain:
```
# Generated by Fabric8 CRDGenerator, manual edits might get overwritten!
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrds.com.example
spec:
  group: com.example
  names:
    kind: MyCRD
    plural: mycrds
    singular: mycrd
  scope: Namespaced
  versions:
  - name: mycrd
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              test:
                enum:
                - A
                - B
                - field1
                type: string
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true

```

### Expected behavior

A crd with just enum values and without enum fields:
```

# Generated by Fabric8 CRDGenerator, manual edits might get overwritten!
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrds.com.example
spec:
  group: com.example
  names:
    kind: MyCRD
    plural: mycrds
    singular: mycrd
  scope: Namespaced
  versions:
  - name: mycrd
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              test:
                enum:
                - A
                - B
                type: string
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true

```

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.22.3@latest

### Environment

Windows
