### ISSUE TITLE
istio Timestamp type should be mapped to String type in java

### ISSUE THREAD

**Issue by yimoucao** [fabric8io/kubernetes-client#4312]
### Describe the bug

in istio generators, there's such code block that converts istio Timestamp to Long
```go
manualTypeMap := map[reflect.Type]string{
		reflect.TypeOf(types.BoolValue{}):   "java.lang.Boolean",
		reflect.TypeOf(types.DoubleValue{}): "java.lang.Double",
		reflect.TypeOf(types.Duration{}):    "java.lang.String",
		reflect.TypeOf(types.Timestamp{}):   "java.lang.Long",
		reflect.TypeOf(types.Int32Value{}):  "java.lang.Integer",
		reflect.TypeOf(types.UInt32Value{}): "java.lang.Integer",
	}
```

according to istio doc, it will be marshaled to string in RFC-3339 string
and one example is `lastTransitionTime` on [istio offical site](https://istio.io/latest/docs/reference/config/config-status/#the-conditions-field:~:text=%3A%0A%20%20%2D%20lastProbeTime%3A%20null-,lastTransitionTime,-%3A%20%222019%2D12%2D26T22%3A06)

strings can't be deserialized into java Long type

### Fabric8 Kubernetes Client version

6.0.0

### Steps to reproduce

copy yaml
```yaml
  - lastProbeTime: null
    lastTransitionTime: "2019-12-26T22:06:34Z"
    message: "61/122 complete"
    reason: "stillPropagating"
    status: "False"
    type: Reconciled
```
and do deserialization with type IstioCondition

### Expected behavior

successful deserialization

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

### Fabric8 Kubernetes Client Logs

```shell
enterprise-customized k8s
```
