### ISSUE TITLE
@SchemaSwap can only be used once

### ISSUE THREAD

**Issue by xRodney** [fabric8io/kubernetes-client#4350]
### Describe the bug

In the [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CRD-generator.md), it is written that it is "Same as SchemaFrom, but can be applied at any point in the class hierarchy"

I also found in [this PR](https://github.com/fabric8io/kubernetes-client/pull/3797): "The annotation serves to enable the use-case where you want to generate a valid CRD from a model that you don't own.". The PR references [keycloak operator](https://github.com/keycloak/keycloak/pull/9759) as an example of such model.

I believe I have a similar-enough use case:
* In my schema, I use a huge object tree (hundreds of fields in dozens of classes) which I do not own.
* Most of the classes are fine, only at a few places I need to tweak things.
* If I owned the classes, I would have just added a few @SchemaFrom's here and there.

I am led to believe that @SchemaSwap is the way how to achieve the same result without editing external code.
For each @SchemaFrom I would like to have on a field of some class I do not own, I would instead put one @SchemaSwap on the root level.

There are two problems with this:

1. @SchemaSwap is not repeatable. I am only entitled to one @SchemaSwap annotation per class. 
2. If the class and field referenced in @SchemaSwap is used multiple times in the class hierarchy, it is only replaced once.

### Fabric8 Kubernetes Client version

5.12.3

### Steps to reproduce

Generate CRD for this schema:

```
@Group("testresource.example.com")
@Version("v1")
@SchemaSwap(originalType = ExternalObject.class, fieldName = "shouldBeInt", targetType = Integer.class)
//@SchemaSwap(originalType = AnotherObject.class, fieldName = "shouldBeString", targetType = String.class)    // does not compile if uncommented
public class TestResource extends CustomResource<ExternalSpec, Void> implements Namespaced {
}

// I do not own these classes:

class ExternalSpec {
    ExternalObject first;
    ExternalObject second;
    AnotherObject third;
}

class ExternalObject {
    String shouldBeInt;
}

class AnotherObject {
    int shouldBeString;
}
```

It generates:

```
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              first:
                properties:
                  shouldBeInt:
                    type: integer
                type: object
              second:
                properties:
                  shouldBeInt:
                    type: string
                type: object
              third:
                properties:
                  shouldBeString:
                    type: integer
                type: object
            type: object
          status:
            type: object
        type: object
```

### Expected behavior

I want all three replacements in my example to happen.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Additional context

I believe these are bugs, rather than limitations by design, and judging from the code, they should not be hard to fix. I may attempt a PR if you agree.

Or am I using them wrong?

Thanks for advice and for a great library!
