### ISSUE TITLE
how to deal with the crd field x-kubernetes-preserve-unknown-fields

### ISSUE THREAD

**Issue by ido2021** [fabric8io/kubernetes-client#4426]
### Describe the bug

I followed the instructions of [Generating Java from CRD](https://github.com/fabric8io/kubernetes-client/blob/master/doc/java-generation-from-CRD.md) and used Dapr's [Component CRD](https://github.com/dapr/dapr/blob/master/charts/dapr/crds/components.yaml)  to generate Java source code.

The CRD has a `value` field that uses `x-kubernetes-preserve-unknown-fields: true`, and the generated source code is as follows:
```
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@com.fasterxml.jackson.annotation.JsonPropertyOrder({})
@com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = com.fasterxml.jackson.databind.JsonDeserializer.None.class)
public class Value implements io.fabric8.kubernetes.api.model.KubernetesResource {

    @com.fasterxml.jackson.annotation.JsonIgnore()
    private java.util.Map<String, Object> additionalProperties = new java.util.HashMap<>();

    @com.fasterxml.jackson.annotation.JsonAnyGetter()
    public java.util.Map<String, Object> getAdditionalProperties() {
        return additionalProperties;
    }

    @com.fasterxml.jackson.annotation.JsonAnySetter()
    public void setAdditionalProperties(java.util.Map<String, Object> additionalProperties) {
        this.additionalProperties = additionalProperties;
    }
}
```

But according to the component example given by Dapr, the value of the `value` field can be String, int, or other:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
    - name: consumerID
      value: "{uuid}"
    - name: url
      value: "tcp://admin:public@localhost:1883"
    - name: qos
      value: 1
    - name: retain
      value: "false"
    - name: cleanSession
      value: "false"

```
So like **value: "tcp://admin:public@localhost:1883"**, how should I set it to Value Class?

### Fabric8 Kubernetes Client version

6.1.1

### Steps to reproduce

...

### Expected behavior

...

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.22

### Environment

Linux
