### ISSUE TITLE
Container environment variables key name restriction  

### ISSUE THREAD

**Issue by mohanpindyala** [fabric8io/kubernetes-client#447]
I am trying to add environment variables for containers , looks like there is restriction for key names 
`[a-zA-Z0-9_]` 
Sample code
` List<EnvVar> envValues = new ArrayList<>();
                for (Map.Entry<String, String> env : envProps.entrySet()) {
                    EnvVar envVar = new EnvVar();
                    envVar.setName(env.getKey());
                    envVar.setValue(env.getValue());
                    envValues.add(envVar);
                }
            container.setEnv(envValues);`

I try to use  key like  `myprop.db.name`  it barfs . Is this client library limitation or k8s itself ?

**Comment by jimmidyson** [comment]
This is actually a restriction on env vars in bash afaik that Kubernetes inherits & validates against. See https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/pkg/api/v1/types.go#L923-L924 & https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/pkg/api/v1/types.go#L42-L46.

**Comment by chenlein** [comment]
@jimmidyson [Kubernetes was relax restrictions on environment variable names.](https://github.com/kubernetes/kubernetes/pull/48986)
Sample code:
```yaml
          env:
            - name: "cluster.name"
              value: "elasticsearch-cluster-1550544058281"
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: "discovery.zen.ping.unicast.hosts"
              value: "elasticsearch-discovery-1550544058281"
            - name: "node.master"
              value: "false"
            - name: "node.data"
              value: "true"
            - name: "ES_JAVA_OPTS"
              value: "-Xms8192m -Xmx8192m"
```
Error message:
```
javax.validation.ConstraintViolationException: Constraint Validations: name must match "^[A-Za-z_][A-Za-z0-9_]*$" on bean: EnvVar(name=cluster.name, value=elasticsearch-cluster-1550544067656, valueFrom=null, additionalProperties={})
```
