### ISSUE TITLE
Schema for multimaps is wrong

### ISSUE THREAD

**Issue by xRodney** [fabric8io/kubernetes-client#4487]
### Describe the bug

Hello again,

after #4413 will have been merged, crd generator will no longer fail on multimaps, which are present in keycloak-operator crds.

Unfortunately, they will still be generated wrong.

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

(same as in #4357)

```
@Group("map.fabric8.io")
@Version("v1alpha1")
public class ContainingMaps extends  CustomResource<ContainingMapsSpec, Void> {}

public class ContainingMapsSpec {
  private MyMultiMap<String, String> test3;
}

public class MyMultiMap<K, V> extends HashMap<K, List<V>> {}
```

The field `test3` is treated as if it was `Map<String, String>`:

```
      openAPIV3Schema:
        properties:
          status:
            type: object
          spec:
            properties:
              test3:
                additionalProperties:
                  type: string
                type: object

```

### Expected behavior

The field `test3` should be treated as if it was `Map<String, List<String>>`:

```
 openAPIV3Schema:
        properties:
          status:
            type: object
          spec:
            properties:
              test3:
                additionalProperties:
                  items:
                    type: string
                  type: array
                type: object



```

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Additional context

Compared to #4413, this is rather low severity, as it can easily be worked around using `@SchemaFrom` and/or `@SchemaSwap`.

In my assessment, this should be improved in sundrio and I have already filed an issue there (sundrio/sundrio#341) and a PR (sundrio/sundrio#342). If I'm right and my contribution is merged, here we should only upgrade sundrio and maybe add a test and a changelog entry.
