### ISSUE TITLE
[java-generator] No default value generated if `x-kubernetes-preserve-unknown-fields` is defined.

### ISSUE THREAD

**Issue by andreaTP** [fabric8io/kubernetes-client#4600]
### Describe the bug

The `java-generator` is not emitting the corresponding default value in case `additionalProperties` is defined.
We would need to double-check the behavior with `AnyType` too.

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

Generate the Java code for a CRD with this snippet:

```yaml
                deploymentStrategy:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  description: |-
                    The deployment strategy to use to replace existing pods with new ones.
                    For more information see https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
                  default:
                    type: 'RollingUpdate'
                    rollingUpdate:
                      maxSurge: '25%'
                      maxUnavailable: '25%'
```

the result is:

```java
public class DeploymentStrategy implements io.fabric8.kubernetes.api.model.KubernetesResource {

    @com.fasterxml.jackson.annotation.JsonIgnore()
    private java.util.Map<String, Object> additionalProperties = new java.util.HashMap<>();

    @com.fasterxml.jackson.annotation.JsonAnyGetter()
    public java.util.Map<String, Object> getAdditionalProperties() {
        return additionalProperties;
    }

    @com.fasterxml.jackson.annotation.JsonAnySetter()
    public void setAdditionalProperties(java.util.Map<String, Object> additionalProperties) {
        this.additionalProperties = additionalProperties;
    }
}
```

but the default value is not respected.

### Expected behavior

The default value should be encoded correctly.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

next (development version)

### Environment

other (please specify in additional context)
