### ISSUE TITLE
[java-generator] CRD names are inconsistent in case of explicit plural

### ISSUE THREAD

**Issue by andreaTP** [fabric8io/kubernetes-client#4611]
### Describe the bug

The CRD Java classes generated by the `java-generator` are not respecting the original `Singular` and `Plural`.

This is making the client unexpectedly fail with `Not Found` errors like:

```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://localhost:8080/apis/broker.amq.io/v2alpha5/namespaces/lala/activemqartemis. Message: Not Found.
```

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

with a CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  name: activemqartemises.broker.amq.io
spec:
  group: broker.amq.io
  names:
    kind: ActiveMQArtemis
    listKind: ActiveMQArtemisList
    plural: activemqartemises
    singular: activemqartemis
  scope: Namespaced
```

after generating the code you obtain:

```java
jshell> import io.amq.broker.v1beta1.*

jshell> var x = new ActiveMQArtemis()
x ==> ActiveMQArtemis()

jshell> x.getCRDName()
$3 ==> "activemqartemis.broker.amq.io"

jshell> x.getSingular()
$4 ==> "activemqartemis"

jshell> x.getPlural()
$5 ==> "activemqartemis"
```

### Expected behavior

This is the expected output instead:
```java
jshell> import io.amq.broker.v1beta1.*

jshell> var x = new ActiveMQArtemis()
x ==> ActiveMQArtemis()

jshell> x.getCRDName()
$3 ==> "activemqartemises.broker.amq.io"

jshell> x.getSingular()
$4 ==> "activemqartemis"

jshell> x.getPlural()
$5 ==> "activemqartemises"
```

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

next (development version)

### Environment

macOS

### Additional context

Bug found originally by @michalxo 🙏
