### ISSUE TITLE
Java generator inserts a literal string where an enum constant is expected

### ISSUE THREAD

**Issue by adriansuarez** [fabric8io/kubernetes-client#4664]
### Describe the bug

If an enum field in a CRD has a default value, then the Java code generated by java-gen contains an assignment of a string literal to an enum variable, which cannot be compiled.

### Fabric8 Kubernetes Client version

6.3.0

### Steps to reproduce

1. Create a CRD that has an enum field with a default value. For example:
```
...
                  dataRetentionPolicy:
                    default: Delete
                    description: ...
                    enum:
                    - Delete
                    - Retain
                    type: string
...
```
2. Generate Java code using java-gen or the Maven plugin.
3. The resulting Java code will look like this:
```
    public enum DataRetentionPolicy {

        @com.fasterxml.jackson.annotation.JsonProperty("Delete")
        DELETE("Delete"), @com.fasterxml.jackson.annotation.JsonProperty("Retain")
        RETAIN("Retain");

        java.lang.String value;

        DataRetentionPolicy(java.lang.String value) {
            this.value = value;
        }
    }

    /**
     * ...
     */
    @com.fasterxml.jackson.annotation.JsonProperty("dataRetentionPolicy")
    @com.fasterxml.jackson.annotation.JsonPropertyDescription("...")
    @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SKIP)
    private DataRetentionPolicy dataRetentionPolicy = "Delete";
```

### Expected behavior

I would expect an initialization statement that compiles and also generates a valid enum constant at runtime, e.g.
```
    private DataRetentionPolicy dataRetentionPolicy = DataRetentionPolicy.DELETE;
```
or
```
    private DataRetentionPolicy dataRetentionPolicy = DataRetentionPolicy.valueOf("Delete".toUpperCase());
```

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Fabric8 Kubernetes Client Logs

```shell
K8s version is irrelevant. This is just a code generation issue.
```
