### ISSUE TITLE
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.20.0.1:443/apis/extensions/v1beta1/namespaces/testing/ingresses. Message: Not Found.

### ISSUE THREAD

**Issue by Maciej-Monster** [fabric8io/kubernetes-client#4738]
### Describe the bug

I am struggling with an error about `apis/extensions/v1beta1/namespaces`. We use fabric8io for running our K8 tests. When we upgrade K8 version to 1.23 I also upgraded the client&fabric8 libarries versions to 6.3.1, however I am getting below exception and I am a bit confused about it. I haven't found a similar issue, so decided to open a new one.

**I am also aware that it might not be a directly a bug but a kind of misconfiguration on my side (?), although I am looking for any kind of tips here.**

K8 changelog and removal of v1beta1 - https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: [https://172.20.0.1:443/apis/extensions/v1beta1/namespaces/testing/ingresses](https://172.20.0.1/apis/extensions/v1beta1/namespaces/testing/ingresses). Message: Not Found.
```

I know that v1beta1 was deprecated and newer version of the endpoint should be used - https://kubernetes.io/docs/reference/using-api/deprecation-guide/

Source code:
```
val client: KubernetesClient = KubernetesClientBuilder().build()
val service = client.services().inNamespace("testing").withName(serviceLabel)
val httpUrl = service.getURL("dynamodb")
```

### Fabric8 Kubernetes Client version

6.3.1

### Steps to reproduce

Run below code on AWS K8 1.23
```
// serviceLabel is calculated at runtime
val client: KubernetesClient = KubernetesClientBuilder().build()
val service = client.services().inNamespace("testing").withName(serviceLabel)
val httpUrl = service.getURL("dynamodb")
```

k8.yml
```
apiVersion: v1
kind: Namespace
metadata:
  name: testing
  labels:
    name: testing
---
apiVersion: v1
kind: Service
metadata:
  name: integration-test
  namespace: testing
  labels:
    role: init
spec:
  type: NodePort
  ports:
    - name: dynamodb
      port: 8000
      targetPort: 8000
  selector:
    role: init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-test
  namespace: testing
spec:
  selector:
    matchLabels:
      role: init
  replicas: 1
  template:
    metadata:
      labels:
        role: init
    spec:
      containers:
        - name: dynamodb
          image: amazon/dynamodb-local:1.16.119
          ports:
            - containerPort: 8000

```

### Expected behavior

No errors, v1beta3 is used instead of v1beta1

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.23

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: [https://172.20.0.1:443/apis/extensions/v1beta1/namespaces/testing/ingresses](https://172.20.0.1/apis/extensions/v1beta1/namespaces/testing/ingresses). Message: Not Found.
```
