### ISSUE TITLE
Java generation from CRD Yaml with required fields does not compile

### ISSUE THREAD

**Issue by ryanemerson** [fabric8io/kubernetes-client#4822]
### Describe the bug

If a CRD contains properties with a `required` array defined, then the generated Java code does not compile due to:

```
target/generated-sources/java/io/example/v1alpha1/examplespec/datasource/SecretRef.java:[13,37] package io.fabric8.generator.annotation does not exist
```

If the `required` field is removed from the CRD then the generated code compiles as expected.

### Fabric8 Kubernetes Client version

6.4.1

### Steps to reproduce

1. Define minimal CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: example.io
spec:
  group: example.io
  names:
    kind: Example
    listKind: ExampleList
    plural: examples
    singular: example
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Example is the Schema for the Examples API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Describes the desired configuration for a Example. Only DB
              Example Service is supported atm
            properties:
              dataSource:
                description: DatasourceRef or a ServiceBindingRef (TODO clarify)
                properties:
                  secretRef:
                    description: Reference to a local secret containing DB connection
                      details.
                    properties:
                      name:
                        description: Resource name
                        type: string
                    required:
                      - name
                    type: object
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```

2. Generate and compile code

### Expected behavior

That the generated code would compile when the `required` element is present.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux
