### ISSUE TITLE
NullPointerException in OpenIDConnectionUtils if no `idp-certificate-authority-data` present in AuthProvider config

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#4960]
### Describe the bug

I was testing token refresh on an IBM Cloud cluster using KubernetesClient, I was using OIDC config like this:

```yaml
users:
- name: "foo@example.com/5cb1/iam.cloud.ibm.com-identity"
  user:
    auth-provider:
      config:
        client-id: "kube"
        client-secret: "kube"
        id-token: "********"
        idp-issuer-url: "https://iam.cloud.ibm.com/identity"
        refresh-token: "********"
      name: "oidc"
```

But during refresh I was getting NPE on this line : 
https://github.com/fabric8io/kubernetes-client/blob/f64529c40eeb8138497f58650b0cfdc3c39a7a7c/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java#L273

Looks like for getting Issuer ID certificate, we are only relying on AuthProviderConfig:
https://github.com/fabric8io/kubernetes-client/blob/f64529c40eeb8138497f58650b0cfdc3c39a7a7c/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java#L88

We should change this line to pick cert data from Config in case it's not present in AuthProvider config:
```dif
String idpCert = currentAuthProviderConfig.getOrDefault(IDP_CERT_DATA, currentConfig.getCaCertData());
```

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

Try to test token refresh with some cluster config where `idp-certificate-authority-data` is not present in AuthProvider config. 

### Expected behavior

KubernetesClient should default to certificate data from cluster in case it's not present in auth provider config

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux
