### ISSUE TITLE
Cluster scoped CRD generated with implements Namespaced

### ISSUE THREAD

**Issue by asafza** [fabric8io/kubernetes-client#5023]
### Describe the bug

When generating Java code for a cluster scoped CRD, the root Java object implements Namespaced.

### Fabric8 Kubernetes Client version

6.5.1

### Steps to reproduce

Generate Java code for the following CRD:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
spec:
  scope: Cluster
metadata:
  name: xxx.xxx.com
spec:
  names:
    plural: xxxs
    singular: xxx
    kind: Xxx
```

### Expected behavior

Class Xxx is not expected to implement the interface Namespaced.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS
