### ISSUE TITLE
Authentication issue in exec credentials with kube config

### ISSUE THREAD

**Issue by mmolinero-ob** [fabric8io/kubernetes-client#5035]
### Describe the bug

In class io.fabric8.kubernetes.client.Config there is a method with a authentication version harcoded. In kubernetes 1.25 the versions supported by the lib are deprecated.

```  
protected static ExecCredential getExecCredentialFromExecConfig(ExecConfig exec, File configFile)
      throws IOException, InterruptedException {
    String apiVersion = exec.getApiVersion();
    if ("client.authentication.k8s.io/v1alpha1".equals(apiVersion)
        || "client.authentication.k8s.io/v1beta1".equals(apiVersion)) {
      List<ExecEnvVar> env = exec.getEnv();
      // TODO check behavior of tty & stdin
      ProcessBuilder pb = new ProcessBuilder(
          getAuthenticatorCommandFromExecConfig(exec, configFile, Utils.getSystemPathVariable()));
      pb.redirectErrorStream(true);
      if (env != null) {
        Map<String, String> environment = pb.environment();
        env.forEach(var -> environment.put(var.getName(), var.getValue()));
      }
      Process p = pb.start();
      String output;
      try (InputStream is = p.getInputStream()) {
        output = IOHelpers.readFully(is);
      }
      if (p.waitFor() != 0) {
        LOGGER.warn(output);
      }
      ExecCredential ec = Serialization.unmarshal(output, ExecCredential.class);
      if (!apiVersion.equals(ec.apiVersion)) {
        LOGGER.warn("Wrong apiVersion {} vs. {}", ec.apiVersion, apiVersion);
      } else {
        return ec;
      }
    } else { // TODO v1beta1?
      LOGGER.warn("Unsupported apiVersion: {}", apiVersion);
    }
    return null;
  }
```

This two lines don't support the current version api "client.authentication.k8s.io/v1" and this throws the error "Unsupported apiVersion:"
```
    if ("client.authentication.k8s.io/v1alpha1".equals(apiVersion)
        || "client.authentication.k8s.io/v1beta1".equals(apiVersion)) {
```

### Fabric8 Kubernetes Client version

6.5.1

### Steps to reproduce

We need a user in .kube/config with exec commands to reproduce. We are getting the token with aws user.

Example:
```
- name: developer
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - dev
      command: aws
      env:
      - name: AWS_PROFILE
        value: developer
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

We receive the error:
"Unsupported apiVersion: client.authentication.k8s.io/v1"

### Expected behavior

Get a valid token of kubernetes cluster.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
2023-04-06 11:33:37.542  WARN 23753 --- [           main] io.fabric8.kubernetes.client.Config      : Unsupported apiVersion: client.authentication.k8s.io/v1
2023-04-06 11:33:37.544  WARN 23753 --- [           main] io.fabric8.kubernetes.client.Config      : No token returned
```
