### ISSUE TITLE
[java-generator] additionalProperties: true ignored

### ISSUE THREAD

**Issue by miriSch** [fabric8io/kubernetes-client#5145]
### Describe the bug

if the CRD yaml contains a field of type object with `additionalProperties: true`, the generated java classes have no field for the additional properties

### Fabric8 Kubernetes Client version

6.6.2

### Steps to reproduce

1. create a maven project with the following files:
    - pom.xml 
      ```
      <?xml version="1.0" encoding="UTF-8"?>
      <project xmlns="http://maven.apache.org/POM/4.0.0"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
          <modelVersion>4.0.0</modelVersion>
      
          <groupId>org.example</groupId>
          <artifactId>javadoc-escape</artifactId>
          <version>1.0-SNAPSHOT</version>
      
          <properties>
              <maven.compiler.source>11</maven.compiler.source>
              <maven.compiler.target>11</maven.compiler.target>
              <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
          </properties>
      
          <dependencies>
              <dependency>
                  <groupId>io.fabric8</groupId>
                  <artifactId>kubernetes-client</artifactId>
                  <version>6.6.2</version>
              </dependency>
              <dependency>
                  <groupId>io.fabric8</groupId>
                  <artifactId>generator-annotations</artifactId>
                  <version>6.6.2</version>
              </dependency>
          </dependencies>
      
          <build>
              <plugins>
                  <plugin>
                      <groupId>io.fabric8</groupId>
                      <artifactId>java-generator-maven-plugin</artifactId>
                      <version>6.6.2</version>
                      <executions>
                          <execution>
                              <goals>
                                  <goal>generate</goal>
                              </goals>
                              <id>crd-generator</id>
                          </execution>
                      </executions>
                      <configuration>
                          <source>${project.basedir}/src/main/resources</source>
                      </configuration>
                  </plugin>
              </plugins>
          </build>
      
      </project>
      ```
    - src/main/java/org/example/Main.java
      ```
      package org.example;

      public class Main {
          public static void main(String[] args) {
              System.out.println("Hello world!");
          }
      }
      ```
    - src/main/resources/example-crd.yaml
       ```
        apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        metadata:
         name: dummies.example.com
        spec:
         group: example.com
         versions:
           - name: v1
             served: true
             storage: true
             schema:
               openAPIV3Schema:
                 type: object
                 properties:
                   spec:
                     type: object
                     properties:
                       withPreserve:
                         description: field without properties but with flag x-kubernetes-preserve-unknown-fields=true
                         type: object
                         x-kubernetes-preserve-unknown-fields: true
                       withPreserveAndProperty:
                         description: field without properties but with flag x-kubernetes-preserve-unknown-fields=true
                         type: object
                         x-kubernetes-preserve-unknown-fields: true
                         properties:
                           fixed:
                             type: string
                       withAdditionalProperties:
                         description: field with additionalProperties
                         type: object
                         additionalProperties: true
                       withStringTypedAdditionalProperties:
                         description: field with string additional properties
                         type: object
                         additionalProperties:
                           type: string
         scope: Namespaced
         names:
           plural: dummies
           singular: dummy
           kind: Dummy
      ```
2. run `mvn clean compile`

### Current behavior:
The generated class com.example.v1.DummySpec has the following fields
- private com.example.v1.dummyspec.WithAdditionalProperties withAdditionalProperties;
- private com.example.v1.dummyspec.WithPreserve withPreserve;
- private com.example.v1.dummyspec.WithPreserveAndProperty withPreserveAndProperty;
- private java.util.Map<java.lang.String, String> withStringTypedAdditionalProperties;

where the generated types of those fields look the following:
- WithAdditionalProperties.java:
  ```
  package com.example.v1.dummyspec;

  @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
  @com.fasterxml.jackson.annotation.JsonPropertyOrder({})
  @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = com.fasterxml.jackson.databind.JsonDeserializer.None.class)
  @javax.annotation.processing.Generated("io.fabric8.java.generator.CRGeneratorRunner")
  public class WithAdditionalProperties implements io.fabric8.kubernetes.api.model.KubernetesResource {
  }
  ```
- WithPreserve.java:
  ```
  package com.example.v1.dummyspec;

  @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
  @com.fasterxml.jackson.annotation.JsonPropertyOrder({})
  @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = com.fasterxml.jackson.databind.JsonDeserializer.None.class)
  @javax.annotation.processing.Generated("io.fabric8.java.generator.CRGeneratorRunner")
  public class WithPreserve implements io.fabric8.kubernetes.api.model.KubernetesResource {

      @com.fasterxml.jackson.annotation.JsonIgnore()
      private java.util.Map<String, Object> additionalProperties = new java.util.HashMap<>();

      @com.fasterxml.jackson.annotation.JsonAnyGetter()
      public java.util.Map<String, Object> getAdditionalProperties() {
          return additionalProperties;
      }

      @com.fasterxml.jackson.annotation.JsonAnySetter()
      public void setAdditionalProperties(java.util.Map<String, Object> additionalProperties) {
          this.additionalProperties = additionalProperties;
      }

      @com.fasterxml.jackson.annotation.JsonAnySetter()
      public void setAdditionalProperty(java.lang.String key, java.lang.Object value) {
          this.additionalProperties.put(key, value);
      }
  }
  ```
- WithPreserveAndProperty.java:
  ```
  package com.example.v1.dummyspec;

  @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
  @com.fasterxml.jackson.annotation.JsonPropertyOrder({"fixed"})
  @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = com.fasterxml.jackson.databind.JsonDeserializer.None.class)
  @javax.annotation.processing.Generated("io.fabric8.java.generator.CRGeneratorRunner")
  public class WithPreserveAndProperty implements io.fabric8.kubernetes.api.model.KubernetesResource {

      @com.fasterxml.jackson.annotation.JsonProperty("fixed")
      @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SKIP)
      private String fixed;

      public String getFixed() {
          return fixed;
      }

      public void setFixed(String fixed) {
          this.fixed = fixed;
      }

      @com.fasterxml.jackson.annotation.JsonIgnore()
      private java.util.Map<String, Object> additionalProperties = new java.util.HashMap<>();

      @com.fasterxml.jackson.annotation.JsonAnyGetter()
      public java.util.Map<String, Object> getAdditionalProperties() {
          return additionalProperties;
      }

      @com.fasterxml.jackson.annotation.JsonAnySetter()
      public void setAdditionalProperties(java.util.Map<String, Object> additionalProperties) {
          this.additionalProperties = additionalProperties;
      }

      @com.fasterxml.jackson.annotation.JsonAnySetter()
      public void setAdditionalProperty(java.lang.String key, java.lang.Object value) {
          this.additionalProperties.put(key, value);
      }
  }
  ```

### Expected behavior

- The field `withAdditionalProperties` of class com.example.v1.DummySpec should be of type `Map<String, Object>`
- The class `WithAdditionalProperties` should not be generated

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Additional context

_no runtime/kubernetes version since this only affects the generator_

-----

The case where `prop.getAdditionalProperties() != null` but `prop.getAdditionalProperties().getSchema() == null` has to be handled here:
https://github.com/fabric8io/kubernetes-client/blob/c76762a58d809d47d5a36734a096eeb74e474f7d/java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java#L200-L201
