### ISSUE TITLE
MultivaluedStringStringHashMap crd representation

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#5244]
From https://github.com/keycloak/keycloak/issues/20937 the schema generated for 

```
public class MultivaluedStringStringHashMap extends HashMap<String, List<String>> {
}
```
The same schema is generated for the original type  MultivaluedHashMap<String, String>.

@andreaTP what is / was the expectation here?

**Comment by shawkins** [comment]
The generated schema either way is:
```
config:
  additionalProperties:
    items:
      type: "string"
    type: "array"
  type: "object"
```
I had missed in my first glance at the keycloakrealmimports crd that the additionalProperties are an array type as expected.  There are also configs present with the schema
```
config:
  additionalProperties:
    type: string
  type: object
```
but those are not the ones targeted by the swaps.

If the MultivaluedHashMap<String, String> schema is now correct, then I'll just remove those schemaswaps in keycloak.
