### ISSUE TITLE
`Cluster()` configuration should use `tlsServerName`

### ISSUE THREAD

**Issue by winitzki** [fabric8io/kubernetes-client#5292]
It seems that `tlsServerName` is not actually being honored in the configuration of the fabric8 kubernetes client. But it seems to be required in my setup to have `tlsServerName`.

Related stackoverflow issue: https://stackoverflow.com/questions/76575638/fabric8-kubernetes-client-cannot-connect-to-cluster-unexpected-end-of-stream

### Is your enhancement related to a problem? Please describe

I am having trouble connecting to a cluster using a `KUBECONFIG` where `tls-server-name` is specified. I have no problem doing `kubectl` commands with this config, but the fabric8 kubernetes client (latest version 6.7.2) is failing to perform any operations due to "end of stream" errors such as these:

`java.io.IOException: unexpected end of stream on Connection{127.0.0.1:6443, proxy=DIRECT hostAddress=/127.0.0.1:6443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}`
`Caused by: java.io.EOFException: \n not found: limit=0 content=…`

My setup is that I have a tunnel from localhost to the kubernetes API server somewhere in AWS.

My config looks like this:

```yamlapiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://127.0.0.1:6443
    tls-server-name: xxx.<redacted>NNNN.us-west-2.aws.host
  name: mycluster
contexts:
- context:
    cluster: mycluster
    namespace: default
    user: kube-aws-admin
  name: mycluster
current-context: mycluster
kind: Config
preferences: {}
users:
- name: kube-aws-admin
  user:
    token: REDACTED
```

I found that `tlsServerName` is being parsed by the code but seems to be never actually used. https://github.com/search?q=org%3Afabric8io++tlsServerName&type=code

Is this the reason I am having trouble?

I found that, if I remove `tls-server-name` from the config, then also `kubectl` is unable to work and gives me  anerror `Unable to connect to the server: EOF`, which is similar to the "end of stream" error shown above.

### Describe the solution you'd like

I'd like to be able to use the fabric8 client normally in the situation where `tls-server-name` is specified in the config.

Code such as this one should work:

```java
new KubernetesClientBuilder().build().pods().inNamespace("mynamespace").list().getItems()
```

The code here defines `Cluster()` class:

https://github.com/fabric8io/kubernetes-client/blob/449d06bc447f2b621149b20312235d2d28460873/kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/Cluster.java#L85

But `getTlsServerName()` is never called in the code:

https://github.com/search?q=repo%3Afabric8io%2Fkubernetes-client%20getTlsServerName&type=code

I am not sure how this is supposed to be used, so I am not able to make a PR myself to fix this problem.

### Describe alternatives you've considered

I tried a lot of different ways of configuring the fabric8 kubernetes client, but none of them worked.

### Additional context

It seems that the official Kubernetes Java client has the same problem. See this issue https://github.com/kubernetes-client/java/issues/1604  

I tested similarly with the official Java client and I get the same response `java.io.IOException: unexpected end of stream on https://127.0.0.1:6443/...` and `Caused by: java.io.EOFException: \n not found: limit=0 content=…`

It may be that the problem is with `okhttp` that somehow needs to be configured properly. But I do not understand what the actual problem is.
