### ISSUE TITLE
CRD Generation - Defaulting Support

### ISSUE THREAD

**Issue by ipvdevs** [fabric8io/kubernetes-client#5410]
While the crd-generator currently supports annotations such as `@Pattern`, `@Min`, `@Max`,  `@Required`, etc, which helps to enforce constraints on CRD fields, there is no way of specifying default values. I would appreciate built-in support for setting default values when generating the CustomResourceDefinition.

Reference: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting

I suggest implementing a mechanism that allows to define such default values for the CRD fields by using annotations, similar to how existing annotations work. For example:

```java
public class MyCustomResourceSpec {
    // ... Other annotations
    @Required
    @DefaultValue("example")
    private String exampleValue;
}
```

Corresponding `default: example` will be generated in the output CRD, such as:

```yaml
properties:
  spec:
    properties:
      exampleValue:
        type: string
        default: "example"
      required:
      - exampleValue
```
