### ISSUE TITLE
CRD generation produces wrong schema for collections

### ISSUE THREAD

**Issue by benkeil** [fabric8io/kubernetes-client#5417]
### Describe the bug

When using the Annotation Processor to generate CRD schema, Collections are not proper mapped.

### Fabric8 Kubernetes Client version

6.8.1

### Steps to reproduce

```kotlin
@Group(Api.domain)
@Version(Api.Versions.v1Alpha1)
@ShortNames("queue", "sqs")
@Kind(SqsQueueManifestV1Alpha1.Kind)
@Labels(Api.Labels.provider)
@JsonDeserialize(using = JsonDeserializer.None::class)
class SqsQueueManifestV1Alpha1 :
    CustomResource<SqsQueueManifestV1Alpha1.Spec, SqsQueueManifestV1Alpha1.Status>(),
    Namespaced,
    KubernetesResource {
  data class Spec(
      @field:JsonPropertyDescription("the name of the queue") @Required val name: String,
      @field:JsonPropertyDescription(
          "in which regions the resources should deployed, default is 'eu-central-1'")
      val regions: Collection<String> = listOf("eu-central-1"),
  )

  data class Status(val queues: Collection<String>)

  companion object {
    const val Kind = "SqsQueue"
  }
}
```

produces:

```yaml
name: v1alpha1
schema:
  openAPIV3Schema:
    properties:
      spec:
        properties:
          name:
            description: the name of the queue
            type: string
          regions:
            description: "in which regions the resources should deployed, default\
              \ is 'eu-central-1'"
            type: object
        required:
        - name
        type: object
      status:
        properties:
          queues:
            type: object
        type: object
    type: object
```

The type of `regions` is `object` but should be `array`

### Expected behavior

`Collection` should be treated as array like (or `List`)

### Runtime

minikube

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS
