### ISSUE TITLE
The CRD generator is not generating spec field default values 

### ISSUE THREAD

**Issue by raminqaf** [fabric8io/kubernetes-client#5454]
### Describe the bug

I am trying to create a CRD with some default values. Let's say my Spec POJO looks like this:
```java
@Data
public class MyAppSpec {
        @Required
        private String name;
        int replicaCount = 1;
}
```

The spec section of the generated CRD looks like this:
```yaml
          spec:
            properties:
              name:
                type: string
              replicaCount:
                type: integer
            required:
            - name
            type: object
          status:
            type: object
        type: object
```
Shouldn't the expected CRD contain a `default: 1` field for the `replicaCount`? Am I missing something?

### Fabric8 Kubernetes Client version

6.8.1

### Steps to reproduce

1. Set up a Java project
2. Create Spec
3. Build project and examine the generated CRD

### Expected behavior

```diff
          spec:
            properties:
              name:
                type: string
              replicaCount:
                type: integer
+               default: 1
            required:
            - name
            type: object
          status:
            type: object
        type: object
```

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS
