### ISSUE TITLE
[java-generator] Default values + x-kubernetes-int-or-string breaks compilation

### ISSUE THREAD

**Issue by andreaTP** [fabric8io/kubernetes-client#5580]
### Describe the bug

When a default is provided for a field of type `IntOrString` the generated code attempts to do a straight assignment to String which is not allowed.

Reported by @kornys

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

A field like:

```yaml
                      pvcSize:
                        anyOf:
                        - type: integer
                        - type: string
                        default: 10Gi
                        description: 'Customize the size of the PVC created for the
                          default MariaDB instance. Default: 10Gi'
```

breaks compilation.

### Expected behavior

Compilation should succeed and the generated code should be immediately usable.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

next (development version)

### Environment

other (please specify in additional context)
