### ISSUE TITLE
How do I obtain a node roles?

### ISSUE THREAD

**Issue by zhaoCarry** [fabric8io/kubernetes-client#5734]
### Describe the bug

How do I obtain a node roles?
<img width="986" alt="image" src="https://github.com/fabric8io/kubernetes-client/assets/46186824/4f8f9cd2-75ed-4a13-9368-cd106db4c466">

### Fabric8 Kubernetes Client version

6.10.0

### Steps to reproduce

k8sClient.nodes()  There is no information about the role

### Expected behavior

can use APIs to obtain node role information

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

**Comment by rohanKanojia** [comment]
@zhaoCarry : When checking node YAML contents, I see only this label from which role could be obtained. Could you please check the kubectl source to see where kubectl is getting this information?

```
- apiVersion: v1
  kind: Node
  metadata:
    labels:
      node-role.kubernetes.io/control-plane: ""
```
What is the value of this label on your machine?
