### ISSUE TITLE
CRDGenerator: Add support for size constraints

### ISSUE THREAD

**Issue by baloo42** [fabric8io/kubernetes-client#5836]
### Is your enhancement related to a problem? Please describe

At the moment the CRDGenerator does not support size constraints:

- minItems
- minProperties
- minLength
- maxItems
- maxProperties
- maxLength

### Describe the solution you'd like

A new annotation `@Size` allows to define min and/or max constraints on a field or its accessors:

```java
@Target({ ElementType.ANNOTATION_TYPE, ElementType.FIELD, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
public @interface Size {
  long min() default 0;
  long max() default Long.MAX_VALUE;
}
```

The CRDGenerator detects this annotation and adds JSONSchema constraints dependending on the java type:

| Java Type  | Constraints                    |
|------------|--------------------------------|
| String     | minLength<br>maxLength         |
| Array/List | minItems<br>maxItems           |
| Map        | minProperties<br>maxProperties |

If the annotation is used on an unsupported type, a warning message is logged.

### Additional context

Size constraints become more important if someone wants to use CEL Validation rules on fields of a CRD.
Because of the cost calculations of a CEL rule, constraints on strings/lists/maps are often only allowed if limits are defined.

**Comment by rohanKanojia** [comment]
@andreaTP : Could you please share your thoughts on this one? Do you think this could be a good addition to CRD Generator?

**Comment by andreaTP** [comment]
Hi @baloo42 and thanks a lot for this proposal.

This intersects with the discussion around CEL and validation, I would prefer to have a(shared) understanding of the final target from this effort before commenting on (perceived?)"sub-tasks" like this one.

Can you please come up with a design proposal along with a mocked/dummy dev-UX sample?

**Comment by baloo42** [comment]
> This intersects with the discussion around CEL and validation, I would prefer to have a(shared) understanding of the final target from this effort before commenting on (perceived?)"sub-tasks" like this one.

In my opinion it is independent of CEL/Kubernetes Validation Rules:
`minLength`/`maxLength`,  `minItems`/`maxItems`, `minProperties`/`maxProperties` are JSON Schema / OpenAPI validation constraints and can be useful even without the combination with Kubernetes Validation Rules.
If we look at other similar projects like [Spring-Doc](https://springdoc.org/#Introduction) / [swagger-core](https://github.com/swagger-api/swagger-core), they implemented such constraints by detecting the JSR-303 annotation `@Size` and adding the appropriate constraints. We should do the same but as previously decided with own annotations:

If a field or one of its accessors is annotated with `io.fabric8.generator.annotation.Size`

```java
public class ExampleSpec {
  @Size(min = 1, max = 3)
  String stringWithLowerAndUpperLimits;
  @Size(min = 1, max = 3)
  List<String> listWithLowerAndUpperLimits;
  @Size(min = 1, max = 3)
  String[] arrayWithLowerAndUpperLimits;
  @Size(min = 1, max = 3)
  Map<String, String> mapWithLowerAndUpperLimits;
}
```

The field will have the `minLength`/`maxLength` or `minItems`/`maxItems` or `minProperties`/`maxProperties` properties in the generated CRD, such as:

```yaml
          spec:
            properties:
              stringWithLowerAndUpperLimits:
                maxLength: 3
                minLength: 1
                type: string
              listWithLowerAndUpperLimits:
                items:
                  type: string
                maxItems: 3
                minItems: 1
                type: array
              arrayWithLowerAndUpperLimits:
                items:
                  type: string
                maxItems: 3
                minItems: 1
                type: array
              mapWithLowerAndUpperLimits:
                additionalProperties:
                  type: string
                maxProperties: 3
                minProperties: 1
                type: object
            type: object
```

see PoC: https://github.com/baloo42/kubernetes-client/pull/4


And what about the relation to Kubernetes Validation rules?

> Size constraints become more important if someone wants to use CEL Validation rules on fields of a CRD.
> Because of the cost calculations of a CEL rule, constraints on strings/lists/maps are often only allowed if limits are defined.

--> see https://kubernetes.io/blog/2022/09/23/crd-validation-rules-beta/#runtime-cost-limits-for-crd-validation-rules

> In addition to the estimated cost limit, CEL keeps track of actual cost while evaluating a CEL expression and will halt execution of the expression if a limit is exceeded.
> 
> With the estimated cost limit already in place, the runtime cost limit is rarely encountered. But it is possible. For example, it might be encountered for a large resource composed entirely of a single large list and a validation rule that is either evaluated on each element in the list, or traverses the entire list.
> 
> CRD authors can ensure the runtime cost limit will not be exceeded in much the same way the estimated cost limit is avoided: by setting maxItems, maxProperties and maxLength on array, map and string types.
