### ISSUE TITLE
Generate a CRD with {type: string, format: date-time}

### ISSUE THREAD

**Issue by matteriben** [fabric8io/kubernetes-client#5867]
### Is your enhancement related to a problem? Please describe

I'd like to generate a CRD with a timestamp of type=string, and format=date-time.

I can generate code from a CRD with a string using date-time format, but when I generate a CRD from that code it generates something else entirely. For example:

Original CRD snippet:
```
                timestamp:
                  type: string
                  format: date-time
```

Java code snippet generated from above CRD snippet:
```
    @com.fasterxml.jackson.annotation.JsonProperty("timestamp")
    @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SKIP)
    private java.time.ZonedDateTime timestamp;

    @com.fasterxml.jackson.annotation.JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ssVV")
    public java.time.ZonedDateTime getTimestamp() {
        return timestamp;
    }

    @com.fasterxml.jackson.annotation.JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss[XXX][VV]")
    public void setTimestamp(java.time.ZonedDateTime timestamp) {
        this.timestamp = timestamp;
    }
```

CRD snippet generated from above Java code snippet:
```
              timestamp:
                properties:
                  dateTime:
                    properties:
                      date:
                        properties:
                          year:
                            type: integer
                        type: object
                      time:
                        properties:
                          nano:
                            type: integer
                        type: object
                    type: object
                  offset:
                    properties:
                      id:
                        type: string
                      totalSeconds:
                        type: integer
                    type: object
                  zone:
                    type: object
                type: object
            type: object
```

### Describe the solution you'd like

I'd like for CRD fields of {type=string, format=date-time} to roundtrip from CRD to Java and back to CRD.
