### ISSUE TITLE
Octal `defaultMode` notation in yaml not properly converted to json

### ISSUE THREAD

**Issue by bearpaws** [fabric8io/kubernetes-client#6110]
### Describe the bug

I'm creating a CronJob from a yaml manifest that contains a ConfigMap volume with octal notation `0555` for the defaultMode.

When creating the resource on the kube server, the API returns this error:
```
CronJob.batch "conf" is invalid: [spec.jobTemplate.spec.template.spec.volumes[0].configMap.defaultMode: Invalid value: 555: must be a number between 0 and 0777 (octal)
```

This worked correctly in version 5.12.4 of the API, however in 6.13.1 it fails.

### Fabric8 Kubernetes Client version

6.13.1

### Steps to reproduce

Yaml manifest that contains a ConfigMap volume:

```yaml
volumes:
- name: resources
  configMap:
    name: conf
    defaultMode: 0555
```

Create the resource via the API:
```java
var resource = Serialization.unmarshal(Files.newInputStream(yamlFile), CronJob.class);

System.out.println(resource.getSpec().getJobTemplate().getSpec().getTemplate().getSpec().getVolumes().get(0).getConfigMap());

client.batch().v1().cronjobs()
  .inNamespace(resource.getMetadata().getNamespace())
  .createOrReplace(resource);
```

In version 5.12.4, it prints:
```
ConfigMapVolumeSource(defaultMode=365 ...)
```

In version 6.13.1, it prints the following and fails with the above error.
```
ConfigMapVolumeSource(defaultMode=555 ...)
```

### Expected behavior

The library should properly convert the octal yaml value into the equivalent value required for json, as it did in previous versions.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Additional context

Related issue:  https://github.com/fabric8io/kubernetes-client/issues/2572

**Comment by manusa** [comment]
If you specify the value as `365`, does it work?

**Comment by bearpaws** [comment]
> If you specify the value as `365`, does it work?

Yes that works.

**Comment by rohanKanojia** [comment]
> This worked correctly in version 5.12.4 of the API, however in 6.13.1 it fails.

@bearpaws : Hello, I'm trying to run this simple test with KubernetesClient v5.12.4 but it's failing with the same error.
```java
  @Test
  @DisplayName("unmarshal, when integer value has octal literal value, then octal literal value correctly deserialized")
  void unmarshal_whenIntegerValueHasOctalLiteralValue_thenCorrectlyDeserializeInteger() {
    // When
    final CronJob cronJob = Serialization.unmarshal(getClass().getResourceAsStream("/cronjob-octal.yml"), CronJob.class);
    // Then
    assertThat(cronJob)
      .extracting(CronJob::getSpec)
      .extracting(CronJobSpec::getJobTemplate)
      .extracting(JobTemplateSpec::getSpec)
      .extracting(JobSpec::getTemplate)
      .extracting(PodTemplateSpec::getSpec)
      .extracting(PodSpec::getVolumes)
      .asInstanceOf(InstanceOfAssertFactories.list(Volume.class))
      .singleElement()
      .extracting(Volume::getConfigMap)
      .hasFieldOrPropertyWithValue("defaultMode", Integer.valueOf("0555", 8))
      .isNotNull();
  }
```

Here is YAML that I'm loading : 

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-db
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-fingerprints
              image: python:3.6.2-slim
              command: ["/bin/bash"]
              args: ["-c", "python /client/test.py"]
              volumeMounts:
                - name: application-code
                  mountPath: /where/ever
          restartPolicy: OnFailure
          volumes:
            - name: resources
              configMap:
                name: conf
                defaultMode: "0555"
```
