### ISSUE TITLE
Configuration should use `proxy-url` if provided in `.kube/config`

### ISSUE THREAD

**Issue by hudac** [fabric8io/kubernetes-client#6150]
### Is your enhancement related to a problem? Please describe

The `~/.kube/config` file supports a [`proxy-url`](https://kubernetes.io/docs/tasks/extend-kubernetes/socks5-proxy-access-api/#client-configuration) attribute per `cluster` entry, like:
```yaml
- cluster:
  name: cluster-eks-42
    server: https://xxx.eks.amazonaws.com
    certificate-authority-data: LS0tLS1...
    proxy-url: socks5://localhost:1080
```

This is currently not taken into account, only env/system properties (i.e. `all.proxy`) apply.

Having this config per cluster is ideal when working with multiple clusters, with different (or for some none) proxy settings.

### Describe the solution you'd like

Getting this per cluster proxy setting in `~/.kube/config` in sync with env/system properties driven proxy settings, I'd suggest that the per cluster setting in `~/.kube/config` should prevail.

For example:
`~/.kube/config`
```yaml
- cluster:
  name: cluster1
    server: https://...
    certificate-authority-data: ...
    proxy-url: socks5://localhost:1080
- cluster:
  name: cluster2
    server: https://...
    certificate-authority-data: ...
    proxy-url: socks5://another-proxy:1080
- cluster:
  name: cluster3
    server: https://...
    certificate-authority-data: ...
```

The expected behaviour should be:
```shell
$ ALL_PROXY=http://default-proxy.local:8080 ./start.sh

> cluster1 -> socks5://localhost:1080
> cluster2 -> socks5://another-proxy:1080
> cluster3 -> http://default-proxy.local:8080
```

```shell
$ unset ALL_PROXY; ./start.sh

> cluster1 -> socks5://localhost:1080
> cluster2 -> socks5://another-proxy:1080
> cluster3 -> * no proxy *
```

### Describe alternatives you've considered

Current workaround is either having different environment variables (when connecting to one cluster per process), or programatically (a must when connecting to more than one cluster within same process).

### Additional context

Tested with `io.fabric8:kubernetes-client:6.13.1`
