### ISSUE TITLE
merge multiple files listed in KUBECONFIG environment var

### ISSUE THREAD

**Issue by adietish** [fabric8io/kubernetes-client#6240]
### Is your enhancement related to a problem? Please describe

One can provide kubectl with multiple kube config files via the `KUBECONFIG` env variable. Kubectl would merge those and let the user use them.
ex. 
* `export KUBECONFIG=${HOME}/.kube/config:${HOME}/.kube/minikube.yaml:${HOME}/.kube/sandbox.yaml`
* empty `~/.kube/config` with only `current-context` pointing to a context that's defined in further file
```yaml
apiVersion: v1
kind: Config
clusters: null
contexts: null
current-context: minikube
preferences: {}
users: null
```
* `~/.kube/minikube.yml`
```yaml
apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority: /Users/adietish/.minikube/ca.crt
      extensions:
        - extension:
            last-update: Wed, 07 Aug 2024 11:05:40 CEST
            provider: minikube.sigs.k8s.io
            version: v1.33.1
          name: cluster_info
      server: https://127.0.0.1:39093
    name: minikube
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Wed, 07 Aug 2024 11:05:40 CEST
            provider: minikube.sigs.k8s.io
            version: v1.33.1
          name: context_info
      namespace: default
      user: minikube
    name: minikube
users:
  - name: minikube
    user:
      client-certificate: /Users/adietish/.minikube/profiles/minikube/client.crt
      client-key: /Users/adietish/.minikube/profiles/minikube/client.key
```
* `~/.kube/sandbox.yml`
```yaml
apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://XXXX.openshiftapps.com:6443
    name: api-sandbox-m3-1530-p1-openshiftapps-com:6443
users:
  - name: adietish/XXXX-openshiftapps-com:6443
    user:
      token: sha256~YYYYYYYY
contexts:
  - context:
      cluster: XXXX-openshiftapps-com:6443
      namespace: adietish-dev
      user: adietish/XXXX-openshiftapps-com:6443
    name: adietish-dev/XXXX-openshiftapps-com:6443/adietish 
```

In kubectl I can then have `config` pointing to minikube or sandbox, both would work. In kubernetes-client, only the 1st file is used which then fails because it is missing url, user, etc.

### Describe the solution you'd like

It would be great if kubernetes-client could merge these files into one config like kubectl does.
