### ISSUE TITLE
Allow for unknown fields in the CRD Spec

### ISSUE THREAD

**Issue by kelhelawy** [fabric8io/kubernetes-client#6739]
Hi,
I know I can use `@PreserveUnknownFields` in fields inside the specs to allow for unknown fields, but is there a way to do so in the specs itself (the parent), not a field inside?
In the CRD it is possible by doing so:

```
spec:
  group: "..."
  names:
    kind: "..."
  scope: "Namespaced"
  versions:
  - name: "v1"
    schema:
      openAPIV3Schema:
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
            properties:
               ....
```
But what would be the equivalent of that from java,
The annotation PreserveUnknownFields is not allowed on type
