### ISSUE TITLE
JsonMappingException: No resource type found for:xxx

### ISSUE THREAD

**Issue by ningyougang** [fabric8io/kubernetes-client#6752]
When load k8s configuration by below codes
```
public KubernetesClient getObject() throws Exception {
    return new DefaultKubernetesClient();
}  

// finally invoke below codes(transfer content to k8s Config)
public static Config parseConfigFromString(String contents) throws IOException {
   ObjectMapper mapper = Serialization.yamlMapper();
   // below is jackjson method
   return mapper.readValue(contents, Config.class);  <----------this line throws below exception
}  
```
exception info:
>com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:xxx.xxx.com/v1beta1#ClusterMetadata
 at [Source: java.io.StringReader@43de88f3; line: 16, column: 7] (through reference chain: io.fabric8.kubernetes.api.model.Config["clusters"]->java.util.ArrayList[0]->io.fabric8.kubernetes.api.model.NamedCluster["cluster"]->io.fabric8.kubernetes.api.model.Cluster["extensions"]->java.util.ArrayList[0]->io.fabric8.kubernetes.api.model.NamedExtension["extension"])

Below is the example of the k8s config located in `~/.kube/config`
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    ################ below part is new added(begin)
    extensions:
    - extension:
        DetailAPI: https://xxx.xxx.com/#/promote/detail?corporateName=xxx&containerSeq=
        ImageResultAPI: ""
        Profile: real
        PromoteAPI: https://xxx.xxx.xxx.com/api/docker/info
        Type: default
        apiVersion: xxx.xxx.com/v1beta1
        kind: ClusterMetadata
        metadata:
          creationTimestamp: null
      name: metadata
     ################ above part is new added(end) 
    server: https://xx.xxx.xxx.com:6443
  name: name1
contexts:
- context:
    cluster: name1
    user: name1
  name: name1
current-context: xxx@xxx
kind: Config
preferences: {}
users:
- name: name1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - login
      command: C:\Users\Administrator\Downloads\xxx.exe
      env:
      - name: XXX_ENDPOINT
        value: https://xxx.xxx.com:5000/v3
      - name: XXX_DOMAIN_ID
        value: default
```

Btw, if i removed below content
```
    ################ below part is new added(begin)
    extensions:
    - extension:
        DetailAPI: https://xxx.xxx.com/#/promote/detail?corporateName=xxx&containerSeq=
        ImageResultAPI: ""
        Profile: real
        PromoteAPI: https://xxx.xxx.xxx.com/api/docker/info
        Type: default
        apiVersion: xxx.xxx.com/v1beta1
        kind: ClusterMetadata
        metadata:
          creationTimestamp: null
      name: metadata
     ################ above part is new added(end) 
```
Can load k8s configuration successfully using jackjson.
