### ISSUE TITLE
Support generating CRDs with logical constraints using [ "oneOf", "allOf", "anyOf", "not" ]

### ISSUE THREAD

**Issue by matteriben** [fabric8io/kubernetes-client#6801]
### Is your enhancement related to a problem? Please describe

I would like to be able to generate a CRD that includes logical constraints using [ "oneOf", "allOf", "anyOf", "not" ].

For example:
```
type: object
properties:
  spec:
    type: object
    properties
      command:
        type: string
      shell:
        type: string
    oneOf:
    - required: [“command”]
    - required: [“shell”]
```

### Describe the solution you'd like

Express these constrains for the CRD generator using java annotations?

For example something like:
```
@OneOf(either = {
  @Alternative(constraints = {
    @Required(name = "command")
  }),
  @Alternative(constraints = {
    @Required(name = "shell")
  })
})
public class ExampleSpec {
  String command;
  String shell;
}
```

### Describe alternatives you've considered

Perhaps these constraints could possibly be expressed through OOP?

For example something like:
```
public abstract class ExampleSpec {
}

public class ExampleSpecCommand extends ExampleSpec {
  String command;
}

public class ExampleSpecShell extends ExampleSpec {
  String shell;
}
```

### Additional context

https://kubernetes.io/blog/2019/06/20/crd-structural-schema/
