### ISSUE TITLE
Generate java required getters for required spec and/or status

### ISSUE THREAD

**Issue by matteriben** [fabric8io/kubernetes-client#6802]
### Is your enhancement related to a problem? Please describe

Required spec/status in CRD is not reflected in generated Java.

### Describe the solution you'd like

I'd like the java generator to add annotated getters for spec/status to the generated custom resource class if the spec/status is required in the CRD.

**Comment by andreaTP** [comment]
Hi @matteriben , I'm not 100% sure about the request here, would you mind drafting a little example with:
- the original CRD
- the current java-generator output
- the expected improvement

afaiu the getters for spec and status are already available ( [e.g.](https://github.com/fabric8io/kubernetes-client/blob/7999cef61a3c7f228a6c2a2dfb5656e889419452/java-generator/it/src/it/ser-deser/src/test/java/io/fabric8/it/certmanager/TestSerialization.java#L50) ).

**Comment by matteriben** [comment]
Hi @andreaTP I'm sorry my original request was not clear without an example.

Given a CRD like this:
```
        openAPIV3Schema:
          type: object
          required:
            - spec
            - status
          properties:
            spec:
              type: object
            status:
              type: object
```

The generator currently creates a class like this:
```
public class Required extends CustomResource<RequiredSpec, RequiredStatus> {
}
```

I'd like the generator to create a class like this:
```
public class Required extends CustomResource<RequiredSpec, RequiredStatus> {

  @java.lang.Override
  @io.fabric8.generator.annotation.Required
  public RequiredSpec getSpec() {
    return super.getSpec();
  }

  @java.lang.Override
  @io.fabric8.generator.annotation.Required
  public RequiredStatus getStatus() {
    return super.getStatus();
  }
}
```

I created a PR which provides an implementation of this requested enhancement:
https://github.com/fabric8io/kubernetes-client/pull/6807
