### ISSUE TITLE
Duplicated values in enum throw IllegalStateException

### ISSUE THREAD

**Issue by heruan** [fabric8io/kubernetes-client#6829]
### Describe the bug

I'm generating class files with Fabric8 Gradle plugin (7.0.1) from the CloudNativePG CRDs (extra annotations enabled). When Sundrio's processes annotations, it fails with:
```
java.lang.IllegalStateException: Found multiple properties in: Action that map to: replace. Properties: Replace and replace!
        at io.sundr.builder.internal.checks.DublicatePropertyCheck.visit(DublicatePropertyCheck.java:28)
```

I assume this is related to this part of the CRD:
```yaml
                      items:
                        description: |-
                          RelabelConfig allows dynamic rewriting of the label set for targets, alerts,
                          scraped samples and remote write samples.
                          
                          More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
                        properties:
                          action:
                            default: replace
                            description: |-
                              Action to perform based on the regex matching.
                              
                              `Uppercase` and `Lowercase` actions require Prometheus >= v2.36.0.
                              `DropEqual` and `KeepEqual` actions require Prometheus >= v2.41.0.
                              
                              Default: "Replace"
                            enum:
                              - replace
                              - Replace
                              - keep
                              - Keep
                              - drop
                              - Drop
```

But I cannot change the CRD nor the generated classes. I've tried setting `uppercaseEnums` both to true and false, same error.

Is it possible for the generator to skip duplicated enums?

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

Run the generator with extra annotations on a CRD that has enums like:
```yaml
                            enum:
                              - replace
                              - Replace
                              - keep
                              - Keep
                              - drop
                              - Drop
```
The enum will be generated as
```java
enum Action {
    REPLACE,
    _REPLACE,
    KEEP,
    _KEEP
    DROP,
    _DROP;
}
```
or, if `enumUppercase=false`, as
```java
enum Action {
    replace,
    Replace,
    keep,
    Keep,
    drop,
    Drop;
}
```
In both cases, Sundrio will fail with:
```
java.lang.IllegalStateException: Found multiple properties in: Action that map to: replace.
```

### Expected behavior

An enum without duplicated value, like:
```java
enum Action {
    REPLACE,
    KEEP,
    DROP;
}
```

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

### Fabric8 Kubernetes Client Logs

```shell

```
