### ISSUE TITLE
The rolling restart of a Deployment or StatefulSet removes the annotations from spec.template.metadata.

### ISSUE THREAD

**Issue by jfreese** [fabric8io/kubernetes-client#6892]
### Describe the bug

The error cased by https://github.com/fabric8io/kubernetes-client/pull/6723/commits

The patch, that is defined in io.fabric8.kubernetes.client.dsl.internal.apps.v1.RollingUpdater.requestPayLoadForRolloutRestart() replaces the hole annotations map found by  `/spec/template/metadata/annotations` and sets the `kubectl.kubernetes.io/restartedAt` annotation. The patch should merge the annotations map instead.

### Fabric8 Kubernetes Client version

7.1.0

### Steps to reproduce

1. Create deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    metadata:
      annotations:
        checksum/event: 8881e757542d422d91cb41b68ff8a0ef60d6cdf22f665b68025d4762575ffb48
```
2. Run `client.apps().deployments().inNamespace("my-namespace").withName("test").rolling().restart()`
3. Get Deployment: annotation `checksum/event` is removed from deployment.

### Expected behavior

1. Create deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    metadata:
      annotations:
        checksum/event: 8881e757542d422d91cb41b68ff8a0ef60d6cdf22f665b68025d4762575ffb48
```
2. Run `client.apps().deployments().inNamespace("my-namespace").withName("test").rolling().restart()`
3. Get Deployment: annotation `checksum/event` exists in the deployment.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell

```

### Additional context

v1.30.2+k0s
