### ISSUE TITLE
Validate YAML when loading it

### ISSUE THREAD

**Issue by ParriePierre** [fabric8io/kubernetes-client#7085]
### Is your enhancement related to a problem? Please describe

Fabric8 does not validate YAML using K8S API. If a field is malformed, it will be ignored. 

As example in the following YAML, podAffinity label selector has a type, trailing "s" is missing in matchLabels : 

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: name
    app.kubernetes.io/version: "1.16.0"
spec:
   replicas: 3
   selector:
     matchLabels:
       app.kubernetes.io/name: test
       app.kubernetes.io/instance: name
   template:
     metadata:
       labels:
         app.kubernetes.io/name: test
         app.kubernetes.io/instance: name
     spec:
       affinity:
         podAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchLabel:
                  app.kubernetes.io/name: test
                  app.kubernetes.io/instance: name
       containers:
         - name: test
           image: "nginx:1.16.0"
           imagePullPolicy: IfNotPresent
           ports:
             - name: http
               containerPort: 80
               protocol: TCP
           livenessProbe:
             httpGet:
               path: /
               port: http
           readinessProbe:
             httpGet:
               path: /
               port: http
```

Applying this YAML using Kubectl result in an error : 

```
$ kubectl apply -f output/out.yaml
Error from server (BadRequest): error when creating "output/out.yaml": Deployment in version "v1" cannot be handled as a Deployment: strict decoding error: unknown field "spec.template.spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector.matchLabel"
```

Applying this YAML using Fabric8 works, Deployment is applied, but matchLabels in PodAffinity is empty, resulting in PodAffinity not being satisfied. 

### Describe the solution you'd like

Add a new method that validate YAML with K8S API when it is loaded : 

```
client.load(yaml).validate().items();
```

That would send a server side apply dry-run apply request with the input YAML to the K8S cluster and return the same error message as K8S.
