### ISSUE TITLE
Issue with LogWatch 

### ISSUE THREAD

**Issue by snjeza** [fabric8io/kubernetes-client#735]
I face the issue when trying to read a log from a pod that doesn't have any logs.

Steps to reproduce:
- create a pod using
```
apiVersion: v1
kind: Pod
metadata:
  name: che-test-pod
spec:
  containers:
  - name: che-180
    image: "rhche/ubuntu_jdk8:latest"
```

- run PodLogExample

The program will take forever.

If you repeat the same test using a pod containing a log, the program will print the log and exit normally.
For more detail, see https://issues.jboss.org/browse/CHE-180

I have tested the 2.2.8 and 2.2.13 versions.
