### ISSUE TITLE
kubernetes-client doesn't support "NetworkPolicy"?

### ISSUE THREAD

**Issue by VFT** [fabric8io/kubernetes-client#739]
```yaml
  apiVersion: extensions/v1beta1
  kind: NetworkPolicy
  metadata:
    name: access-default
  spec:
    podSelector:
      matchLabels:
        ns: default
    ingress:
      - from:
        # - podSelector:
        #     matchLabels:
        #       ns: default
        - namespaceSelector:
            matchLabels:
              ns: default
```
kubernetes-client doesn't support "NetworkPolicy"?

I can't find it in the newest java client.
