### ISSUE TITLE
yaml file which contains multiple resources

### ISSUE THREAD

**Issue by roughbits01** [fabric8io/kubernetes-client#849]
Hello,

Running the following code:
```Java
final List<HasMetadata> resources = client.resourceList(yml).createOrReplace();
```
with a yaml file which contains multiple resources (see bellow) only creates the first resource (in this case the Namespace). How can I load the whole list of resources ?

Thank you in advance!

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: uiot1
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: uiot1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
      - name: worker
        image: localhost:5000/iot-handler-worker:latest
        command: ["/opt/HPE-UIoT/bin/start-worker.sh"]
        args: ["10.0.0.134:9092", "10.0.2.15:2379", "worker.yml"]
        imagePullPolicy: Always
```
