### ISSUE TITLE
PersistentVolumeClaim with storageClass support

### ISSUE THREAD

**Issue by 0312birdzhang** [fabric8io/kubernetes-client#857]
The api seems not support `storageClass`,I cannot create PersistentVolumeClaim with `storageClassName` spec like this:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  storage-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
```

Please help me,is there some way to resolve it. Thanks.

**Comment by 0312birdzhang** [comment]
It's my mistake
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  storage-claim
  annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi

```
