### ISSUE TITLE
Add support for StorageClass

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#869]
Once this https://github.com/fabric8io/kubernetes-model/issues/226 is done....

**Comment by Ferenc-** [comment]
Now that https://github.com/fabric8io/kubernetes-model/issues/226 is closed, I can't wait to see this one closed too. I needed to do a horrible workaround in my business logic to get some makeshift StorageClass "support".

**Comment by Mrwangjinxin** [comment]
Please support it

**Comment by hrishin** [comment]
Add support for [storage](https://kubernetes.io/docs/concepts/storage/storage-classes/) class operations. 
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gluster-vol-default
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.10.100:8080"
  restuser: ""
  secretNamespace: ""
  secretName: ""
allowVolumeExpansion: true
```
Add support for following operations:
 - create stoarge class
 - get storage class
 - delete stoarge class
 - update storage class
