### ISSUE TITLE
Support for different kubernetes and openshift manifest file formats

### ISSUE THREAD

**Issue by hemanik** [fabric8io/kubernetes-client#918]
Support for Kubernetes and OpenShift manifest file format is restrictive. For instance the following file format for multiple resource definition in a single file is acceptable for Kubernetes deployment but is not recognized by Kubernetes client.

```
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    tier: backend
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    tier: backend
    role: master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: gcr.io/google_containers/redis:e2e  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
```
Kubernetes Client supports such files with multiple resource definitions only when given as a list as below:
```
apiVersion: v1
kind: List
items:
  -
    apiVersion: v1
    kind: Service
    metadata:
      name: redis-master
      labels:
        app: redis
        tier: backend
        role: master
    spec:
      ports:
      - port: 6379
        targetPort: 6379
      selector:
        app: redis
        tier: backend
        role: master
  -
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: redis-master
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: redis
            role: master
            tier: backend
        spec:
          containers:
          - name: master
            image: gcr.io/google_containers/redis:e2e  # or just image: redis
            ports:
            - containerPort: 6379
```
## Expected Behaviour
All file formats acceptable by Kubernetes should ideally be supported and if not at least documented somewhere.

## Steps To Reproduce
* Execute the [sample project](https://github.com/hemanik/kubernetes-deployment-testing) with [yaml manifest file.](https://github.com/kubernetes/examples/blob/master/guestbook/all-in-one/guestbook-all-in-one.yaml)
